import { createHash } from 'node:crypto';
import { tool } from 'ai';
import { z } from 'zod';
import { RETAKE_MODELS, DEFAULT_RETAKE_MODEL } from './video-retake-contract';
import { retakeInspectionScope, verifyRetakeInspection, resolveRetakeInspectionReceipt, readRetakeInspectionClock } from './video-retake-inspection';
import { RETAKE_PROMPT_WRITING, retakeShotPlanError } from './video-retake-prompt-planning';
import type { AgentContext } from './agent-tools';
import type { submitMcpVideo } from './billing/mcp-video';
import type { VideoSourceRange } from '@/types';

interface RetakeToolDependencies {
  ctx: AgentContext;
  serializeVideoSubmission: <T>(operation: () => Promise<T>) => Promise<T>;
  resolveSource: (ctx: AgentContext, index: number) => Promise<{ videoUrl?: string; error?: string; sourceRange?: VideoSourceRange }>;
  submit: typeof submitMcpVideo;
}

export function createInspectedRetakeVideoTool({ ctx, serializeVideoSubmission, resolveSource, submit }: RetakeToolDependencies) {
  return tool({
    description: 'Retake an INSPECTED interval of a ready video, automatically delivering the complete video with original audio/duration and footage outside the selection. Call inspect_retake for this exact source/selection/model first, view its frames, then supply its inspection_id plus a concrete source_observation. start/end use original-source seconds. The prompt is the complete final instruction passed directly to the provider without a creative wrapper. Default FAL H3 Max; Seedance 2.5 is available for close motion preservation/small edits. Interval 0.1–15s, source at most 120s; sources under 2s require Seedance. No screenshot relocation, run_code cutting, or second merge confirmation. Poll the returned task; never regenerate to retry delivery.\n' + RETAKE_PROMPT_WRITING,
    inputSchema: z.object({
      media_index: z.number().int().positive(),
      start: z.number().nonnegative(),
      end: z.number().positive(),
      prompt: z.string().min(1).describe('Final expanded prompt: requested visible change first, explicit output-time action/shot beats next, essential identity constraints last. Avoid copying the source synopsis or conflicting camera locks.'),
      shot_plan: z.array(z.object({ start: z.number().nonnegative(), end: z.number().positive(), instruction: z.string().min(1) })).min(1).max(8)
        .describe('Output-local beats matching the final prompt, covering exactly outputSelection from inspect_retake. Do NOT reset its start to zero. Camera edits: one beat per distinct camera; content edits: one persistent beat is enough.'),
      inspection_id: z.string().optional().describe('Exact receipt returned by inspect_retake for this source, range and model. Required before any paid submission.'),
      source_observation: z.string().optional().describe('Timestamped visible evidence: subject identity, original camera coverage, selected opening/middle/closing action states, travel direction/contact/occlusion, and uncertainty. Keep contextual boundary states separate. Do not substitute requested changes for observed facts.'),
      model: z.enum(RETAKE_MODELS).default(DEFAULT_RETAKE_MODEL),
      middle_frame_media_index: z.number().int().positive().optional().describe('H3 camera-change keyframe generated by generate_image with retake_source from an inspected source frame. Read its returned pixels before using it. This is Image 3, also supplied as the native middle frame; Image 1/2 remain source endpoints.'),
      middle_frame_time: z.number().positive().optional().describe('H3 output-local time inside a NEW camera beat, strictly between output first/last frames, usually the middle of the close-up. The native middle frame must match that beat and the source action phase.'),
      request_id: z.string().uuid().optional(),
    }),
    execute: async ({ media_index, start, end, prompt, shot_plan, model, request_id, inspection_id, source_observation, middle_frame_media_index, middle_frame_time }) => serializeVideoSubmission(async () => {
      if (!ctx.userId || !ctx.projectId) return { success: false, message: 'Retake requires an authenticated project.' };
      const source = await resolveSource(ctx, media_index);
      if (!source.videoUrl) return { success: false, message: source.error ?? 'Select a ready video.' };
      if (source.sourceRange && (start < source.sourceRange.start_sec || end > source.sourceRange.end_sec)) {
        return { success: false, message: 'Retake interval must be within the visible original-source range.' };
      }
      const receipt = await resolveRetakeInspectionReceipt(inspection_id,ctx);
      if (!verifyRetakeInspection(receipt, retakeInspectionScope(ctx, source.videoUrl, start, end, model), process.env.SUPABASE_SERVICE_ROLE_KEY || '') || !source_observation || source_observation.trim().length < 24) {
        return { success: false, errorCode: 'retake_inspection_required', message: 'No provider was submitted. Call inspect_retake for this exact media_index/start/end/model, read the actual frames, and provide its inspection_id plus a concrete source_observation before writing the final prompt.' };
      }
      const clock = readRetakeInspectionClock(receipt, retakeInspectionScope(ctx, source.videoUrl, start, end, model), process.env.SUPABASE_SERVICE_ROLE_KEY || '')
      if (!clock) return { success: false, errorCode: 'retake_inspection_required', message: 'No provider was submitted. Re-run inspect_retake to obtain the measured output clock before planning the edit.' }
      const timingError = retakeShotPlanError(shot_plan, prompt, clock.outputSelection)
      if (timingError) return { success: false, errorCode: 'retake_prompt_timing_invalid', message: `No provider was submitted. ${timingError} Required outputSelection: ${clock.outputSelection.start}–${clock.outputSelection.end}s. Correct shot_plan and prompt before submitting.` }
      let middleFrame: {imageUrl:string;time:number} | undefined;
      if (model === 'fal-h3-max' && shot_plan.length > 1 && !middle_frame_media_index) return {success:false,errorCode:'retake_keyframe_required',message:'No video provider submitted. New H3 camera coverage requires a checked image keyframe: call generate_image with retake_source for an actual inspected frame within start/end, write the new camera view while preserving its observed action phase, read the returned image, then supply its middle_frame_media_index and output-local middle_frame_time inside that camera beat. Never use a video poster or contact sheet as the image target.'};
      if (middle_frame_media_index || middle_frame_time != null) {
        const imageUrl = ctx.snapshotImages[middle_frame_media_index! - 1];
        if (model !== 'fal-h3-max' || !imageUrl || !Number.isFinite(middle_frame_time) || middle_frame_time! <= 0 || Math.round(middle_frame_time!*24) >= clock.generationDuration*24-1) return {success:false,message:'Choose a ready H3 image keyframe and a time strictly inside its native output before video submission.'};
        middleFrame = {imageUrl,time:middle_frame_time!};
      }
      const hash = ctx.execution ? createHash('sha256').update(JSON.stringify([ctx.execution.runId, ctx.execution.inputEpoch, media_index, start, end, prompt, model, middleFrame])).digest('hex') : undefined;
      const stableId = hash ? `${hash.slice(0, 8)}-${hash.slice(8, 12)}-4${hash.slice(13, 16)}-a${hash.slice(17, 20)}-${hash.slice(20, 32)}` : undefined;
      const result = await submit({ images: [], script: prompt, videoUrl: source.videoUrl,
        retake: { start, end, ...(middleFrame ? {middleFrame} : {}) }, videoModel: model, projectId: ctx.projectId, billingRequestId: request_id ?? stableId,
      }, { userId: ctx.userId, apiKeyId: null, toolName: 'retake_video' });
      const snapshotId = result.snapshotId ?? result.taskId?.replace(/^video-retake-/, '');
      if (result.success && result.taskId && snapshotId) {
        const row = await ctx.supabase?.from('snapshots').select('video_meta').eq('id', snapshotId).eq('project_id', ctx.projectId).maybeSingle();
        if (row?.data?.video_meta) ctx.pendingVideoSnapshot = { snapshotId, taskId: result.taskId, videoMeta: row.data.video_meta };
      }
      return result;
    }),
  });
}
