import type { RetakePlan } from './video-retake-contract'
import { retakeOutputTime } from './video-retake-inspection'

/** Guidance goes to the inspecting Agent, never appended to a provider prompt. */
export const RETAKE_SCENE_READING = `Read the actual frames in timestamp order. Labels give SOURCE and OUTPUT seconds; JOIN CONTEXT is outside the replacement.
Understand what is visible: subjects, environment, composition, motion, interactions, existing transitions, and the selected opening/closing states. Associate each frame with its own label and evidence group. A new shot in ADJACENT JOIN CONTEXT is not the selected closing state, even if it occurs only one frame later. Describe meaningful changes with supporting timestamps; summarize a static interval once instead of repeating identical frame descriptions. Track event order and physical relationships when relevant. Separate observed facts from uncertain or unseen details; never turn the requested change into a fact about the source.
Read audioEvidence alongside these frames. Attribute speech to its measured source time and distinguish selectedSpeech from adjacentSpeech. Use narration/dialogue to interpret the scene and its intended progression, but do not treat spoken descriptions as visible facts. Spoken names do not establish correct on-screen spelling; inspect displayed letters separately. No speech recognized does not mean no music or sound effects. If ASR is unavailable or untimed, state the limitation and do not invent dialogue, word timing, rhythm or lip-sync evidence.
For additions or selective replacements, inspect the actual usable space and occlusions across the interval, including camera movement. Identify occupied subject/face regions and a feasible route or placement for the new content; distinguish foreground/background and do not assume that a verbal label such as 'above' defines empty space. If text is being corrected, transcribe the visible characters as seen (or state uncertainty), separately from the requested correct string.
Identify what the user wants changed and what must remain coherent. Read adjacent context to understand how this interval enters and exits the surrounding video. Only then plan the edit.`

export const RETAKE_PROMPT_WRITING = `Write a scene-informed edit instruction after viewing the source and any supplied images.
First decide the visible result the user is asking for. Expand only the details needed to make that result clear in this footage: placement, interaction, motion, appearance, duration or presentation. Use the actual source and user intent to choose the edit structure; there is no default shot count, camera sequence, transition or image-generation step. A single continuous instruction is sufficient when the change persists. Split into timed beats only when the requested change develops over time.
Treat requested exclusions and retained attributes as hard constraints, not decorative negatives. For a new object, specify a route through the observed available space, its scale relative to the subjects, and how that route remains clear as subjects and the camera move. Approximate normalized screen regions can help when defensible from the frames; never invent geometry. Do not let the object cross a protected face/body, or change framing/choreography just to make room, when the user requires those to remain. If the footage leaves no feasible space, identify that conflict rather than promising an impossible placement. For a visual operation, describe its observable before/change/after and the distinction from the defective source, so merely repeating the source presentation does not satisfy the requested change.
Keep the source camera and action where they support the request. Change framing, add a shot or use a transition only when requested or needed to express the intended result; do not turn ordinary content edits into multi-camera sequences. If new coverage is appropriate, choose views and pacing based on the actual scene and motion, not a standard template. Distinguish temporal phases from camera changes. For motion or interaction, carry the observed progression into the requested edit: each later beat must continue from the previous action state rather than reintroducing the opening pose. A new camera observes the next phase of the same event, not a second performance. Do not add a landing, impact or other contact unless observed or explicitly requested. Preserve the order of observed events unless the user asks to change them; avoid resets, duplicate events, invented contact or action from the untouched suffix.
Write the requested visible change first, its temporal development if needed next, and only relevant continuity constraints last. Keep the factual observation separate from the provider prompt. Use the measured outputSelection clock; choose all beats within that interval, with enough time to see the result. Do not prescribe cuts or a return-to-source shot merely to fill the time.
Honor the roles of supplied images: content reference, desired intermediate state or explicit final frame. If readable text or UI layout is part of the requested result, inspect and copy the supplied content accurately, keep the lettering stable during its readable display, and animate its placement or surrounding scene rather than morphing characters. When a supplied image is the approved complete replacement scene and the request requires its content/layout, prefer using that existing image as an H3 intermediate visual-state control at a meaningful interior beat, instead of only mentioning it as a loose style reference. An isolated product reference or an image requested only for its style stays a creative reference. This does not require generating an additional image. Choose the role from the image and user intent, not from a fixed workflow. Reuse suitable supplied images directly. A new image is optional support for a missing visual state, not a prerequisite of video editing or camera changes. Generate one only when it materially helps this particular edit and no suitable existing image is available; inspect it before use. If a control or generation capability is unsupported, choose a supported route and explain the relevant limitation.
When the requested result depends on precise readable lettering, a specific layout or a structurally different visual state that the source references do not show, assess whether a verified visual checkpoint would make that state more reliable than text alone. If useful, create it from an inspected source frame, preserving the relevant scene/identity while making the requested difference unmistakable; check the actual letters, geometry and requested content before using it. This is an optional decision for the particular missing state, never a step for every edit. Do not describe complete duplicate source images as independently changed components, or preserve a defective attribute merely because it appears in a continuity reference. Endpoint continuity retains the relevant composition/action, not defects the user explicitly asks to correct; if native source locks prevent that correction, use a supported editing route rather than promising contradictory constraints.
Choose edit_mode from the user's intent, before selecting camera coverage. The generic GUI/time-range envelope 'replace these seconds with' or '把这一段换成' alone does not mean discarding the shot; classify the actual requested change after that envelope. modify edits the existing sequence internally: preserve the original first/last frame states and composition, and express the requested change between them, including when adding multiple views or layers. A camera change does not authorize discarding these endpoint states. Plan a brief coherent entry from the original opening and return to the original closing, while keeping the requested change clear for the meaningful interior duration; avoid replaying the action or stretching a still frame. replace is an explicit request to discard this shot or change its whole scene/action/framing: create a complete new shot, with no requirement to restore the old opening or closing. Preserve only identities or attributes relevant to the user's request; the original environment/action is not mandatory if the user asks to replace it. Do not force an old-camera return or mark a replacement as failed merely because endpoints differ. Adjacent footage is context for editing, not a hidden endpoint constraint in replace mode.
For H3 modify, Image 1 anchors the selected opening and Image 2 anchors the closing; camera_change can omit the competing source-camera video while preserving these native endpoint locks. For H3 replace, Image 1 and Image 2 are references only for retained subject attributes, NOT desired first/last compositions; expressly state what is retained and what is replaced. An optional native middle control is Image 3 and requires modify. Seedance uses the cropped original source video: describe the same modify/replace endpoint policy explicitly in the final instruction. Use supplied timeline markers for creative images so the tool binds them to provider inputs. If an existing image is explicitly the final whole-video frame, pass end_frame_media_index with a selection reaching the source end; transition into that actual asset, not a generated substitute. Such an explicit final-frame constraint takes priority over the old closing state.
For narrated footage, anchor relevant reveals, actions and transitions to measured selectedSpeech output/word times, so visual retiming and assembly restore them against the original source speech. Match meaning as well as timing: a spoken list is not a default sequence of unrelated visual objects or layers. Use a sentence-level idea when individual keywords do not describe the requested visual event; do not force false one-word/one-object correspondences merely to fill the interval. Use only the words actually overlapping the selection; surrounding sentence text is context, not permission to replay it. Preserve the original narration and dialogue; do not request newly generated speech, music or lip movement merely to illustrate narration. ASR alone cannot verify music beats, effects or lip synchronization. If the requested change contradicts retained dialogue or requires changing the audio, explain that scope conflict rather than claiming audiovisual synchronization. If ASR failed and speech understanding is essential to the request, obtain usable audio evidence before submission instead of guessing.
Before the one paid submission, check that the requested change will be perceptible, references and constraints agree, timing fits the measured interval, audiovisual meaning/timing agrees with the retained speech, and the opening/closing handoff follows the user's intent. A completed provider task alone does not establish a successful edit.`

export interface RetakeShotBeat { start: number; end: number; instruction: string }

/** A source/join timestamp describes inspected footage, not output timing. */
function sourceClockReference(prompt: string, index: number): boolean {
  const clause = prompt.slice(Math.max(0,index-100),index).split(/[;\n.!?]/).at(-1) || ''
  return /\b(?:source|original|adjacent|untouched)\b|原片|源片|原视频|原視頻/i.test(clause)
    && !/\boutput\b|输出|輸出|出力/i.test(clause)
}

/** Reject an edit planned in selected-relative time before it can be charged. */
export function retakeShotPlanError(shots: RetakeShotBeat[] | undefined, prompt: string, selection: { start: number; end: number }): string | null {
  const epsilon = .01
  if (!shots?.length || shots.length > 8) return 'Provide shot_plan with 1–8 output-time beats (one persistent beat for a simple content edit).'
  let cursor = selection.start
  for (const shot of shots) {
    if (!Number.isFinite(shot.start) || !Number.isFinite(shot.end) || shot.end <= shot.start
      || Math.abs(shot.start - cursor) > epsilon || shot.start < selection.start - epsilon || shot.end > selection.end + epsilon
      || !shot.instruction?.trim()) return 'shot_plan must continuously cover outputSelection, with no gaps, overlaps or out-of-range beats.'
    cursor = shot.end
  }
  if (Math.abs(cursor - selection.end) > epsilon) return 'shot_plan must end at outputSelection.end.'
  // Only explicit second-based beats are interpreted. Camera dimensions,
  // subjects and other numbers in ordinary prose are not timestamps.
  const ranges = /\b(\d+(?:\.\d+)?)\s*(?:s|秒)?\s*[–—-]\s*(\d+(?:\.\d+)?)\s*(?:s(?:ec(?:onds)?)?\b|秒)/gi
  for (const match of prompt.matchAll(ranges)) {
    if (sourceClockReference(prompt,match.index!+match[0].search(/\d/))) continue
    const start = Number(match[1]), end = Number(match[2])
    if (start < selection.start - epsilon || end > selection.end + epsilon || end <= start) return 'Prompt shot times fall outside outputSelection. Do not reset the selected interval to zero.'
  }
  const points = /(?:\b(?:at|before|after|output(?:-local)?)\s*(?:output\s*)?|(?:输出|輸出|出力)\s*|(?:在|於|于|第)\s*(?:输出|輸出|出力)?\s*)(\d+(?:\.\d+)?)\s*(?:s(?:ec(?:onds)?)?\b|秒)/gi
  for (const match of prompt.matchAll(points)) {
    if (sourceClockReference(prompt,match.index!+match[0].search(/\d/))) continue
    const time = Number(match[1])
    if (time < selection.start - epsilon || time > selection.end + epsilon) return 'Prompt cut time falls outside outputSelection. Do not reset the selected interval to zero.'
  }
  return null
}

export function retakePromptPlanning(plan: RetakePlan) {
  return {
    selectedSourceSeconds: { start: plan.start, end: plan.end },
    outputSelection: { start: retakeOutputTime(plan, plan.start), end: retakeOutputTime(plan, plan.end) },
    promptClock: `Output 0s corresponds to source ${plan.outputMode === 'selection' ? plan.start : plan.contextStart}s. The edit starts at output ${retakeOutputTime(plan, plan.start)}s and ends at output ${retakeOutputTime(plan, plan.end)}s. Do NOT reset this selection to zero. Copy these output times into shot_plan and the final prompt.`,

  }
}
