-- Home Skills Marketplace

CREATE TABLE IF NOT EXISTS home_skills (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  labels jsonb NOT NULL DEFAULT '{}',
  image text NOT NULL,
  prompt text NOT NULL DEFAULT '',
  skill_path text,
  image_count integer DEFAULT 1,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE home_skills ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public read" ON home_skills FOR SELECT USING (true);

-- Seed data
INSERT INTO home_skills (labels, image, prompt, skill_path, image_count, sort_order) VALUES
  ('{"zh":"照片变视频","en":"Photo to Video"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/photo-to-video.jpg', 'Turn my photo into a cinematic short video with dramatic camera movement', NULL, 1, 0),
  ('{"zh":"动态表情包","en":"Animated GIF"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/animated-gif.gif', 'Turn our selfie into a fun animated GIF with expressive movements', NULL, 1, 1),
  ('{"zh":"进击的巨人","en":"Attack on Titan"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/attack-on-titan.jpg', 'Put me on top of the Wall from Attack on Titan, wearing the Survey Corps green cloak with Wings of Freedom emblem, 3D maneuvering gear on my waist, looking back at camera with a determined fearless expression. Behind me the skinless Colossal Titan head looms over the wall, steam pouring from its muscles. Dramatic orange sunset sky, ruined city far below. Epic cinematic wide shot, my figure small against the massive titan.', NULL, 1, 2),
  ('{"zh":"破屏而出","en":"Glass Shatter"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/glass-shatter.jpg', 'Transform my photo into a dramatic action shot — I am punching straight through a glass screen toward the viewer, my fist thrust forward in the center of the frame with glass shards exploding outward frozen in mid-air. Give me bleached blonde messy hair, a black leather jacket, a bruise under one eye, and a fierce angry snarl. Teal and warm orange backlight rim-lighting my silhouette. Dark warehouse background. HBO Original Series logo in bottom-left corner. Shot with ultra-wide lens making my fist look huge.', NULL, 1, 3),
  ('{"zh":"鱿鱼游戏","en":"Squid Game"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/squid-game-player.jpg', 'Put me in the Squid Game Red Light Green Light scene — I am wearing the green tracksuit #456, running toward camera with a terrified but determined expression. A woman with shoulder-length black hair in tracksuit #067 runs beside me on my left. Behind us, the giant robotic doll in yellow and orange dress towers over the sandy field, her head turned toward us. Other players in green tracksuits frozen mid-run in the background. Harsh overhead floodlights, overcast sky, dust kicked up. Netflix cinematic quality.', NULL, 1, 4),
  ('{"zh":"咒术回战","en":"Jujutsu Kaisen"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/jujutsu-gojo.jpg', 'Place me standing back-to-back with photorealistic 3D CGI Gojo Satoru from Jujutsu Kaisen on a destroyed Shibuya rooftop at night. I am on the left wearing a black leather jacket, arms crossed with a confident smirk. Gojo is on the right — tall, white spiky hair, black blindfold, dark blue high-collar uniform, one hand raised with blue Infinity sphere spinning. Purple cursed energy lightning cracks across the dark stormy sky, a dark curse silhouette lurks in the clouds. "SHIBUYA INCIDENT" text at the bottom. Movie poster composition, both figures equally prominent.', NULL, 1, 5),
  ('{"zh":"龙猫森林","en":"Totoro Forest"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/totoro-forest.jpg', 'Put me sitting on the big furry belly of a massive photorealistic CGI Totoro in a lush ancient forest. I am leaning back against his soft grey fur, laughing with mouth wide open and pure joy. Totoro has his iconic wide toothy grin. Tiny black soot sprites (susuwatari) float all around us. The Catbus (furry cat-shaped bus with glowing eyes) peeks from between mossy tree trunks in the background. Golden sunlight streams through the giant camphor tree canopy. I am wearing a denim jacket and converse sneakers. Studio Ghibli live-action movie quality.', NULL, 1, 6),
  ('{"zh":"海贼王·尼卡","en":"One Piece Gear 5"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/onepiece-gear5.jpg', 'Put me on the wooden deck bow of the Thousand Sunny pirate ship, running and laughing wildly with mouth wide open next to a photorealistic 3D CGI Luffy in Gear 5 Sun God Nika form — white rubbery cartoon-like skin, wild flowing white hair upward, huge exaggerated grin, white shirt open showing abs, purple sash. We are side by side, both mid-stride. I am wearing a black crop top with a skull-and-crossbones Straw Hat logo and denim shorts. Massive stormy ocean waves crash behind us, wind blowing our hair dramatically.', NULL, 1, 7),
  ('{"zh":"千与千寻","en":"Spirited Away"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/spirited-away-train.jpg', 'Place me standing barefoot on railway tracks that stretch across an endless calm ocean, looking back over my shoulder at camera with a gentle mysterious smile, long dark hair flowing in the wind. I am wearing a white summer dress. An old weathered red Japanese train approaches from behind in the distance, its headlights on. Shallow water covers the wooden track ties creating perfect mirror reflections of the pink and orange sunset sky. The scene is serene and dreamlike. Spirited Away sea train brought to life as a photograph. Golden hour warm lighting.', NULL, 1, 8),
  ('{"zh":"铁王座","en":"Iron Throne"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/iron-throne-dragon.jpg', 'Put me sitting on the Iron Throne from Game of Thrones — legs crossed, hands gripping the sword armrests, chin raised with a cold commanding stare directly at camera. I am wearing a red latex high-slit dress, a thin gold crown, sharp bob haircut with blunt bangs, bold red lips, gold shimmer on my cheekbones. A small dragon perches on my right shoulder breathing a burst of fire. Dark gothic stone throne room lit only by candles and fire braziers. The mood is dangerous, seductive, and regal.', NULL, 1, 9),
  ('{"zh":"巨人化","en":"Titan Transform"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/titan-half-face.jpg', 'Extreme close-up of my face filling the entire frame — the left half is my real face with smudged dark eyeliner, a lip ring, battle scars, and an intense unblinking stare. The right half seamlessly morphs into an Attack on Titan titan form: exposed red muscles and tendons, no skin, one glowing green eye, steam rising where skin meets muscle along the center split line. "THE RUMBLING" text in large white font at the top. Warm sunset city skyline blurred in the background. Movie poster quality.', NULL, 1, 10),
  ('{"zh":"攻壳机动队","en":"Ghost in the Shell"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/ghost-in-shell.jpg', 'Shot directly from above looking straight down — I am lying on my back in a shallow neon-lit puddle on a Tokyo rooftop at night. My platinum blonde hair fans out like Medusa tendrils in the dark water. I am wearing a sheer black mesh bodysuit with chrome chain harness across my chest, gripping the center ring with both hands. My eyes are wide open staring straight up at the camera with an intense provocative gaze. Neon reflections in the water — cyan, magenta, green — from surrounding signs. Holographic Japanese kanji (電脳, 攻殻) and UI overlays glow around me. Rain droplets frozen mid-air.', NULL, 1, 11),
  ('{"zh":"鱿鱼游戏 VIP","en":"Squid Game VIP"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/squid-game-vip.jpg', 'Put me walking down the center of a neon-lit pink corridor from Squid Game VIP area. I am wearing a perfectly tailored black suit with black shirt, a gold ornate owl mask pushed up onto my forehead, adjusting my right cufflink with a cold arrogant smirk. Flanking me on each side: a Squid Game guard in hot pink jumpsuit — left guard has a triangle mask, right guard has a circle mask, both standing at rigid attention with hands behind back. The corridor recedes behind me with repeating rectangular pink and green fluorescent light frames.', NULL, 1, 12),
  ('{"zh":"时间冻结","en":"Time Freeze"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/time-freeze.jpg', 'Transform my photo into a zero-gravity frozen moment — I am jumping mid-air in the center of a living room with a huge surprised laugh, arms and legs spread wide. Everything around me is suspended in zero gravity: a white coffee mug with brown coffee splashing out frozen mid-splash, an iPhone floating screen-on, white AirPods hovering, cereal pieces scattered like confetti, newspaper pages mid-flutter, polaroid photos floating, and an orange tabby cat mid-leap with arched back to my right. Warm morning sunlight from a large window behind me. Ultra-wide angle lens from low angle.', NULL, 1, 13),
  ('{"zh":"摩天蜘蛛侠","en":"Skyscraper Climb"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/skyscraper-spiderman.jpg', 'Put me crouching on the vertical glass wall of a skyscraper at night, defying gravity like Spider-Man. I am wearing a dark bomber jacket and cargo pants, white sneakers planted flat against the glass. My hair falls sideways from gravity. I am looking directly at camera with a cocky confident grin. Below me (appearing as sideways) the city streets are 50+ stories down — tiny cars, neon signs, streetlights stretching into the distance. The shot is taken from a drone at the same height, creating a vertigo-inducing perspective where the building wall looks like the ground.', NULL, 1, 14),
  ('{"zh":"水晶球女王","en":"Snow Globe"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/snow-globe-queen.jpg', 'Place me inside a giant crystal snow globe installed in the middle of Times Square New York at night. I am sitting elegantly on a golden crescent moon inside the sphere, wearing a flowing red sparkly ball gown. Artificial snow swirls around me inside the glass. Outside the globe, a crowd of people in winter coats stands watching and taking photos with their phones held up — shot from behind the crowd looking in at me. The globe glows warmly from within (golden light) contrasting the cold blue LED billboards of Times Square behind.', NULL, 1, 15),
  ('{"zh":"反重力宫殿","en":"Anti-Gravity"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/anti-gravity-palace.jpg', 'Place me sitting calmly in an ornate golden chair on the ceiling of a baroque palace room — I am upside down relative to the floor. I am wearing a tailored black suit with a loosened black tie, legs crossed casually, one hand resting on the chair arm. My hair and tie hang downward (toward the floor above me). Below me (the actual floor), crystal chandeliers hang upward as if gravity is reversed. Renaissance ceiling frescoes are behind my head. The room has teal and gold color palette. Disorienting Inception-style perspective — the viewer cannot tell which way is up.', NULL, 1, 16),
  ('{"zh":"女帝约会","en":"Boa Hancock Date"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/boa-hancock-bar.jpg', 'Put me sitting at a dark moody bar counter, sipping whiskey from a rocks glass with a slight knowing smirk. Next to me sits a photorealistic 3D CGI Boa Hancock from One Piece — impossibly beautiful with long straight black hair, glowing pink heart-shaped eyes (her love-love beam), red silk qipao top, gold snake earrings. She is leaning toward me with an adoring expression. Warm amber tungsten bar lighting, rows of backlit whiskey bottles blurred in the bokeh background. Intimate date night atmosphere.', NULL, 1, 17),
  ('{"zh":"18号公路","en":"Android 18"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/android18-desert.jpg', 'Place me leaning against a chrome motorcycle on an empty desert highway at golden hour. Next to me stands a photorealistic 3D CGI Android 18 from Dragon Ball Z — sharp blonde bob haircut, piercing icy blue eyes, denim vest over a striped shirt, arms crossed with her signature cold confident expression. I am wearing a black leather jacket, matching her crossed-arms cool attitude. Dusty desert road stretches to the horizon, warm golden backlight, dust particles in the air. Cinematic wide shot, both of us equally prominent.', NULL, 1, 18),
  ('{"zh":"02自拍","en":"Zero Two Selfie"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/zerotwo-selfie.jpg', 'Make it look like I am taking a selfie with photorealistic 3D CGI Zero Two from Darling in the Franxx. She has long pink hair, small red horns on a white headband, bright emerald green eyes, and is doing her playful tongue-out lick toward the camera. She wears her red and white military pilot suit (partially unzipped) and is wrapping one arm possessively around my neck, pulling me close. I am blushing and grinning. Cherry blossom trees behind us with pink petals falling everywhere. Bright spring sunlight, shallow depth of field. Selfie camera angle (slightly above, close-up).', NULL, 1, 19),
  ('{"zh":"玛奇玛天台","en":"Makima Rooftop"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/makima-rooftop.jpg', 'Put me sitting on a concrete rooftop ledge at night in Tokyo. Next to me crouches a photorealistic 3D CGI Makima from Chainsaw Man — she has auburn red-brown hair in long braids, distinctive yellow ringed spiral eyes that glow faintly, wearing a white dress shirt, black necktie, and dark overcoat. She is reaching toward me and holding my chin with one finger, tilting my face toward her with a cold, knowing, seductive smile. I look mesmerized and slightly nervous. Tokyo skyline glitters far below behind us. Dark moody cinematic lighting with a red color accent from a neon sign.', NULL, 1, 20),
  ('{"zh":"墨镜双胞胎","en":"Sunglasses Twinning"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/sunglasses-twinning.jpg', 'Put matching white oversized retro sunglasses on my pet, same style as mine. We are both looking at camera with the same sassy duck-face attitude. Keep the same framing, lighting, and background. The pet should look like it is posing on purpose. Fun twinning moment, bright playful energy.', NULL, 1, 21),
  ('{"zh":"洒红节","en":"Holi Festival"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/holi-portrait.jpg', 'Cover me in vibrant Holi festival color powder — thick splashes of pink, teal green, bright orange, and yellow across my face, buzzed hair, and white linen shirt. Add a garland of pink and cream flowers draped around my neck. I look serene with a calm proud expression, chin slightly raised, looking off to the side. Dramatic warm side-lighting from the left against a deep matte purple background. The colored powder looks freshly thrown and still dusty. Editorial portrait photography quality, sharp focus on every powder grain.', NULL, 1, 22),
  ('{"zh":"夜拍闪光","en":"Night Flash"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/night-flash.jpg', 'Night photography with flash, urban street style', NULL, 1, 23),
  ('{"zh":"像素风","en":"Pixel Art"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/pixel-art.jpg', 'Pixel art style retro gaming aesthetic, 16-bit detailed scene', NULL, 1, 24),
  ('{"zh":"贴纸设计","en":"Sticker"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/sticker.jpg', 'Cute kawaii sticker design with thick outline and pastel colors', NULL, 1, 25),
  ('{"zh":"美食摄影","en":"Food Photo"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/food-photo.jpg', 'Dramatic food photography with studio lighting, commercial advertising style', NULL, 1, 26),
  ('{"zh":"黑白双人肖像","en":"B&W Couple"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/bw-couple-portrait.jpg', 'High-contrast black and white romantic couple portrait — pure white background, intimate pose, fashion editorial quality', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/skills/bw-couple-portrait.zip', 1, 27),
  ('{"zh":"黑白人猫肖像","en":"B&W Woman & Cat"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/bw-woman-cat-portrait.jpg', 'Intimate black and white portrait of a woman and her cat — nose-to-nose touching, warm indoor setting, emotional connection', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/skills/bw-woman-cat-portrait.zip', 1, 28),
  ('{"zh":"夜店钻石风","en":"Diamond Bling"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/nightclub-diamond-bling.jpg', 'Nightclub diamond bling portrait — neon purple/blue lighting, iced-out grillz, luxury watches, Cuban link chains, hip-hop aesthetic', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/skills/nightclub-diamond-bling.zip', 1, 29),
  ('{"zh":"粉丝周边","en":"Fan Merch"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/fan-merch.jpg', 'Design fan merchandise from my photo — phone cases, standees, keychains, banners, badges, stickers', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/skills/fan-merch.zip', 1, 30),
  ('{"zh":"应援大楼","en":"Idol Building"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/idol-building.jpg', 'Idol fan support poster on building scenes — LED screens, subway walls, building facades', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/skills/idol-building.zip', 1, 31),
  ('{"zh":"偶像合照","en":"Idol Selfie"}', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/covers/idol-selfie.jpg', 'Composite selfie with your idol — backstage, concert, photo booth scenes', 'https://sdyrtztrjgmmpnirswxt.supabase.co/storage/v1/object/public/images/marketplace/skills/idol-selfie.zip', 1, 32);
