import { describe, expect, it } from 'vitest'
import { readFileSync } from 'fs'
import path from 'path'

const root = path.resolve(__dirname, '..')

function read(rel: string) {
  return readFileSync(path.join(root, rel), 'utf8')
}

describe('agent prompt policy guards', () => {
  it('keeps image work on generate_image unless editable runtime is explicit', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('Default tool: `generate_image`')
    expect(agent).toContain('Static charts, infographics, posters, and marketing images go to `generate_image`')
    expect(agentTs).toContain('\\`runtime: "composition"\\`: Remotion/editable composition draft')
    expect(agentTs).toContain('\\`runtime: "design"\\` or omitted: legacy alias for \\`runtime: "composition"\\`')
    expect(agentTs).toContain('\\`runtime: "node"\\`: open backend Node with FFmpeg/FFprobe')
    expect(agentTs).toContain('props-first editable text/image/video/trim contract lives in \\`prompts/remotion-composition.md\\`')
    expect(agentTs).toContain('runtime infers and persists it from natural prop reads')
    expect(agentTs).toContain('Do not add editables to \\`runtime:"node"\\` media exports')
    expect(agentTs).toContain('studio.assertCompositionConsumesVisualAssets')
    expect(agentTs).toContain("overrides.assets ?? await loadStudioArtifact('assets')")
    expect(agentTs).toContain('Studio draft promotion requires persisted Storyboard and Assets artifacts')
    expect(agentTs).not.toContain('text editables must read from \\`props[propKey]\\`')
    expect(agentTs).not.toContain('video trim editables must declare \\`trimBeforePropKey/trimAfterPropKey\\`')
  })

  it('keeps preview_frame as one public tool with Remotion and FFmpeg engines', () => {
    const agentTs = read('src/lib/agent.ts')

    expect(agentTs).toContain('Remotion compositions are rendered with Remotion; raw uploaded/generated videos are extracted with FFmpeg')
    expect(agentTs).toContain('For raw video snapshots: use timestamp')
    expect(agentTs).toContain('When design_path is provided it is authoritative; media_index is ignored')
    expect(agentTs).toContain('const targetMediaIndex = design_path')
    expect(agentTs).toContain("source: 'video'")
    expect(agentTs).toContain("source: 'composition'")
    expect(agentTs).toContain('Render succeeded. Treat this as a successful preview_frame result')
    expect(agentTs).toContain('Continue with write_file when the user asked to publish')
    expect(agentTs).not.toContain('extract_video_frame: tool')
  })

  it('does not inject canned run_code narration into CUI messages', () => {
    const agentTs = read('src/lib/agent.ts')
    const en = read('src/lib/locales/en.ts')
    const zh = read('src/lib/locales/zh.ts')

    expect(agentTs).toContain("translate(responseLocale, 'agent.status.generatingCode')")
    expect(en).toContain("'agent.status.generatingCode': 'Generating code...'")
    expect(zh).toContain("'agent.status.generatingCode': '代码生成中...'")
    expect(agentTs).not.toContain('I am writing the Remotion code now')
    expect(agentTs).not.toContain('I am adjusting the code and checking the result')
    expect(agentTs).not.toContain('getRunCodeIntro')
  })

  it('keeps Remotion composition code in the local runtime shape', () => {
    const remotion = read('src/lib/prompts/remotion-composition.md')

    expect(remotion).toContain('Never write')
    expect(remotion).toContain('export default')
    expect(remotion).toContain('function Composition(props)')
    expect(remotion).toContain('Do not use ES module syntax')
    expect(remotion).toContain('remains previewable/publishable even if the tool also returns non-blocking')
    expect(remotion).toContain('Do not rewrite scenes merely to clear advisories')
    expect(remotion).toContain('persisted Storyboard and Assets manifest are an execution contract')
    expect(remotion).toContain('do not regenerate it, silently replace it with CSS/SVG/procedural graphics')
  })

  it('returns resolved generate_image URLs for Remotion composition use', () => {
    const agentTs = read('src/lib/agent.ts')

    expect(agentTs).toContain('Resolved image URL:')
    expect(agentTs).toContain('Use this URL directly in Remotion composition props/code')
    expect(agentTs).toContain('do not use the <<<media_${mediaIndex}>>> marker inside composition code')
  })

  it('uses full timeline snapshots when materializing Remotion compositions', () => {
    const agentTs = read('src/lib/agent.ts')

    expect(agentTs).toContain("select('id, type, design_path')")
    expect(agentTs).toContain('const available = snaps?.length || 0')
    expect(agentTs).toContain('Invalid index ${input.media_index}. Available: 1-${available}.')
    expect(agentTs).toContain('not an editable Remotion composition')
  })

  it('routes voiceover through the single Seed Audio tool', () => {
    const agentTs = read('src/lib/agent.ts')
    const audio = read('src/lib/prompts/audio.md')

    expect(agentTs).toContain('generate_audio: tool({')
    expect(agentTs).toContain('kind: z.enum([\'voiceover\', \'dialogue\', \'music\', \'sound_design\', \'mixed\'])')
    expect(agentTs).not.toContain('generate_voiceover: tool({')
    expect(agentTs).not.toContain('list_voiceover_voices: tool({')
    expect(agentTs).not.toContain('generate_music: tool({')
    expect(audio).toContain('Use `kind: "voiceover"` only when')
    expect(audio).toContain('Voice Performance Brief')
    expect(audio).toContain('do not switch providers')
    expect(audio).toContain('Canonical mixed performance score')
    expect(audio).toContain('[MUSIC — continuous backbone]')
    expect(audio).toContain('[VOICE — line-level performance]')
    expect(audio).toContain('[SFX — in narrative order]')
    expect(audio).toContain('[MIX]')
    expect(audio).toContain('Every spoken line gets its own local performance direction')
    expect(audio).toContain('validated V3 baseline')
    expect(audio).toContain('Duck by no more than 1-2 dB')
    expect(audio).toContain('shorten narration rather than sacrificing the score')
  })

  it('surfaces generated audio progress and playable cards in CUI', () => {
    const agentTs = read('src/lib/agent.ts')
    const reconnect = read('src/hooks/useAgentRun.ts')
    const zh = read('src/lib/locales/zh.ts')

    expect(agentTs).toContain('formatGeneratedAudioForCui')
    expect(agentTs).toContain("kind === 'voiceover' ? 'agent.status.generatingVoiceover' : 'agent.status.generatingAudio'")
    expect(zh).toContain("'agent.status.generatingVoiceover': '生成配音中...'")
    expect(zh).toContain("'agent.status.generatingAudio': '生成音频中...'")
    expect(agentTs).toContain('formatMusicLine')
    expect(agentTs).toContain('music:${safeTrackIndex}|${title}|${safeDuration}|${tags}|${playUrl}|${finalUrl}')
    expect(agentTs).toContain('All voiceover content is generated by Seed Audio')
    expect(agentTs).toContain("kind: z.enum(['voiceover', 'dialogue', 'music', 'sound_design', 'mixed'])")
    expect(agentTs).not.toContain('waitForPreview: true')
    expect(agentTs).not.toContain("provider=\"suno\"")
    expect(agentTs).not.toContain("provider: z.enum(['auto', 'evolink-seed-audio', 'suno'])")
    expect(agentTs).toContain('deductSeedAudioCredits')
    expect(agentTs).toContain('providerCreditsUsed: result.creditsUsed')
    expect(agentTs).not.toContain("deductCredits(ctx.userId ?? '', null, 'create_music')")
    expect(agentTs).toContain('const generatedAudioLine = formatGeneratedAudioForCui(toolName, toolOutput, responseLocale)')
    expect(reconnect).toContain("case 'music_task'")
    expect(reconnect).toContain('callbacks.onMusicTask?.')
  })

  it('keeps uploaded video auto-analysis in the tool-aware history path', () => {
    const editor = read('src/components/Editor.tsx')
    const agentRoute = read('src/app/api/agent/route.ts')

    expect(editor).toContain('First call analyze_video with media_index')
    expect(editor).toContain('First call analyze_video for each uploaded video media_index')
    expect(editor).toContain("analyze_video's result is persisted in agent_tool_history")
    expect(editor).not.toContain("handleAgentRequest('', undefined, undefined, { silent: true, uploadedVideoCount")
    expect(agentRoute).toContain('const isNormalMode = !tipsTeaser && !nameProject && !previewsReady && !tipReaction && !analysisOnly')
  })

  it('runs a trusted Skill template through the final result while preserving ordinary confirmation', () => {
    const agent = read('src/lib/prompts/agent.md')
    const animate = read('src/lib/prompts/animate.md')
    const agentTs = read('src/lib/agent.ts')
    const skillLaunchContext = read('src/lib/skill-launch-context.ts')
    const editor = read('src/components/Editor.tsx')
    const home = read('src/app/home/page.tsx')
    const executionRunner = read('src/lib/agent-execution-runner.ts')

    expect(agent).toContain('Only call `generate_animation` after the user confirms a visible script')
    expect(animate).toContain('in an ordinary CUI/editor request, write the complete visible script and wait for confirmation')
    expect(animate).toContain('the system prompt explicitly supplies a `Trusted Skill template launch`')
    expect(agentTs).toContain('trusted Skill template launch exception')
    expect(skillLaunchContext).toContain('Active Skill: ${context.skillName}')
    expect(skillLaunchContext).toContain('skills/${context.skillName}/SKILL.md')
    expect(editor).toContain('pendingSkill && !pendingSkillLaunchContext')
    expect(home).toContain('createHomeSkillLaunchContext(homeSkill, prompt, skillName)')
    expect(home).toContain('createHomeSkillLaunchContext(homeSkill, draft.prompt, skillName)')
    expect(home).toContain("throw new Error(installData.error || 'Failed to install Skill template')")
    expect(agentTs).toContain('getSkillLaunchSystemDirective(options?.skillLaunchContext)')
    expect(read('src/app/api/agent/route.ts')).toContain('Skill template launch could not be verified')
    expect(read('src/app/api/agent/run/route.ts')).toContain('Skill template launch could not be verified')
    expect(agentTs).toContain("translate(responseLocale, 'status.submittingVideo')")
    expect(agentTs).not.toContain("code: 'skill_video_submission_pending'")
    expect(executionRunner).not.toContain("input.terminal?.code === 'skill_video_submission_pending'")
  })

  it('reconnects text-only CUI projects before the first snapshot exists', () => {
    const editor = read('src/components/Editor.tsx')

    expect(editor).toContain('enabled: !!projectId && !inactive')
    expect(editor).not.toContain('enabled: !!projectId && (initialSnapshots?.length ?? 0) > 0')
  })

  it('keeps built-in image skill triggers visible before the image guide is read', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')
    const tool = read('src/lib/prompts/generate_image_tool.md')
    const image = read('src/lib/prompts/image.md')

    expect(agent).toContain('prompts/enhance.md')
    expect(agent).toContain('skill: "enhance"')
    expect(agent).toContain('prompts/creative.md')
    expect(agent).toContain('skill: "creative"')
    expect(agent).toContain('prompts/wild.md')
    expect(agent).toContain('skill: "wild"')
    expect(agent).toContain('prompts/captions.md')
    expect(agent).toContain('skill: "captions"')

    expect(tool).toContain('read only that one skill prompt file once')
    expect(tool).toContain('Do not read `prompts/image.md` just to route the skill')
    expect(tool).not.toContain('prompts/enhance.md')
    expect(image).toContain('backend no longer injects the full template automatically')
    expect(agentTs).not.toContain('template rules are auto-injected')
    expect(agentTs).toContain('you must have read and internalized that skill prompt once')
  })

  it('leaves named-platform Skill selection to general Agent routing instead of backend keyword rules', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('explicitly named destination, platform, format, or installed Skill')
    expect(agent).toContain('read the destination-specific Skill first')
    expect(agent).toContain('it may then delegate to the generic workflow')
    expect(agent).toContain('Exercise this routing judgment in the Agent')
    expect(agent).toContain('do not wait for backend keyword rules')
    expect(agentTs).not.toContain('getImplicitSkillSystemDirective')
    expect(agentTs).not.toContain('implicit-skill-routing')
  })

  it('requires script confirmation before video provider submission unless direct-submit is explicit', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('video rendering has a script review gate unless the user explicitly asks to submit/render without confirmation')
    expect(agent).toContain('Only call `generate_animation` after the user confirms')
    expect(agent).toContain('Direct-submit exception')
    expect(agent).toContain('直接提交渲染')
    expect(agent).toContain('不要问我确认')
    expect(agent).not.toContain('Do not add a review loop')
    expect(agent).not.toContain('even if the user says "直接提交" or "不要确认"')

    expect(agentTs).toContain('explicitly authorizes direct submission without confirmation')
    expect(agentTs).toContain('直接提交渲染')
  })

  it('treats invalid Seedance reference images as terminal input errors', () => {
    const agent = read('src/lib/prompts/agent.md')
    const animate = read('src/lib/prompts/animate.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain("read_file('prompts/animate.md')")
    expect(animate).toContain('width and height each 300-6000px')
    expect(animate).toContain('`too_small`, `too_large`')
    expect(animate).toContain('`retryable: false` means do not resubmit the same URL')
    expect(animate).toContain('A second unchanged submission becomes `terminal: true`')
    expect(agentTs).toContain('If repairable=true, decide whether to prepare a new compliant image URL')
  })

  it('keeps single video generation in the model duration range and routes longer requests to the director skill', () => {
    const agent = read('src/lib/prompts/agent.md')
    const animate = read('src/lib/prompts/animate.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('Hard duration range: a single SeeDance 2.0 script/call must be 4-15s; SeeDance 2.5 must be 4-30s')
    expect(agent).toContain('If requested/source duration is shorter than the model minimum, use the minimum')
    expect(agent).toContain('If output is longer than the selected model max, use `skills/long-video-director/SKILL.md`')
    expect(agent).toContain("Single-script rule: if a complete approved script is within the selected model's single-generation limit")
    expect(agent).toContain('Do not submit only one shot or split just because it has multiple shot lines')
    expect(agent).toContain("Long source video rule: if an existing timeline/reference video is longer than the selected model's input limit")
    expect(agent).toContain('do not compress the whole source into one short edit')
    expect(agent).toContain('Reference video input limit: one SeeDance 2.0 generation may use up to 15s combined source/reference video duration; SeeDance 2.5 allows up to 30s combined')
    expect(agent).toContain('dimensions 300-6000px')
    expect(agent).toContain('409,600-2,086,876 frame pixels')
    expect(agent).toContain('Kling accepts one .mp4/.mov, <=200MB, <=2K')
    expect(agent).toContain('keep the output duration aligned with the combined source duration shown in Media Index')
    expect(agent).toContain('Clamp to the selected SeeDance range: 4-15s for 2.0, 4-30s for 2.5')

    expect(animate).toContain('Every SeeDance 2.0 script must be **4 to 15 seconds**')
    expect(animate).toContain('Seedance 2.5 scripts may be **4 to 30 seconds** in one call')
    expect(animate).toContain('keep it as **one video generation script**')
    expect(animate).toContain('If the script totals less than 4s, extend it to a compact 4s script instead of submitting a shorter duration')
    expect(animate).toContain('The whole title + every `Shot N (Xs):` line + `Style:` line must be submitted together')
    expect(animate).toContain('Do not submit only a single shot or a single line from the script')
    expect(animate).toContain('Multiple shots are normal inside one 15s video')
    expect(animate).toContain('exactly 16-30s and selects Seedance 2.5')
    expect(animate).toContain("If the source/reference video itself is longer than the selected model's input limit")
    expect(animate).toContain('For longer sources, use the long-video-director workflow instead of one short compressed edit')
    expect(animate).toContain('**30 seconds for Seedance 2.5**')
    expect(animate).toContain('For anything beyond the selected model limit, use the long-video-director workflow')
    expect(animate).toContain('frame pixels width*height between 409,600 and 2,086,876')
    expect(animate).toContain('Kling docs do not state a video resolution lower bound')
    expect(animate).toContain('Never write or submit a SeeDance generated video duration below 4s')

    expect(agentTs).toContain('SeeDance/SeeDance Mini and MiniMax H3 are 4-15 seconds')
    expect(agentTs).toContain('For native SeeDance or MiniMax H3 text-to-video')
    expect(agentTs).toContain('For one MiniMax H3 generation, up to 3 reference videos may be used')
    expect(agentTs).toContain('MiniMax H3 reference videos must each be .mp4/.mov, <=50MB, width and height each 256-5760px')
    expect(agentTs).toContain('MiniMax H3 accepts up to 9 reference images')
    expect(agentTs).toContain('Native SeeDance or MiniMax H3 text-to-video uses no media markers')
    expect(agentTs).toContain('Reference audio is only supported by Seedance video models or MiniMax H3')
    expect(agentTs).toContain('Seedance 2.5 is 4-30 seconds; SeeDance 2.0 is 4-15 seconds')
    expect(agentTs).toContain('Kling is 5-15 seconds')
    expect(agentTs).toContain("If a complete script fits the selected model's single-call limit, submit it as one video generation call")
    expect(agentTs).toContain('Put the whole title, every \\`Shot N (Xs):\\` line, and the \\`Style:\\` line into the same \\`story_prompt\\`')
    expect(agentTs).toContain('Do not submit only one shot, the first shot, or one line from the script')
    expect(agentTs).toContain("Total duration must fit the selected model's capability")
    expect(agentTs).toContain('Long source video rule')
    expect(agentTs).toContain("if a timeline/reference video is longer than the selected model's input limit")
    expect(agentTs).toContain('combined source duration must be at most 15 seconds for SeeDance 2.0 or 30 seconds for SeeDance 2.5')
    expect(agentTs).toContain('frame pixels width*height between 409,600 and 2,086,876')
    expect(agentTs).toContain('Kling video references must be <=200MB and <=2K; no explicit lower resolution is documented')
    expect(agentTs).toContain("clamped to 4-15s for SeeDance 2.0 or 4-30s for SeeDance 2.5")
    expect(agentTs).not.toContain('Duration in seconds: 3, 5, 7, 10, or 15')
    expect(agentTs).not.toContain("The model's minimum generation duration is 5 seconds")
  })

  it('routes video by duration before activating semantic production skills', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')
    const workspace = read('src/lib/workspace.ts')
    const longVideoDirector = read('src/skills/long-video-director/SKILL.md')

    expect(agent).toContain('The skill manifest routes clear matches')
    expect(agent).toContain('read `skills/NAME/SKILL.md`')
    expect(agent).toContain('that Skill owns its workflow')
    expect(agent).toContain("Video routes by the selected model's duration limit first")
    expect(agent).toContain('SeeDance 2.0 is <=15s')
    expect(agent).toContain('SeeDance 2.5 generation may be 4-30s')
    expect(agent).toContain('read `prompts/animate.md` and use `generate_animation`')
    expect(agent).toContain('Model selection happens after workflow routing')
    expect(agent).not.toContain('matched built-in Composition requests route to that editable workflow')
    expect(agentTs).toContain('A video up to and including 15 seconds stays on direct \\`generate_animation\\`')
    expect(agentTs).not.toContain('resolveVideoWorkflowRoute')
    expect(agentTs).not.toContain('videoWorkflowRoute')
    expect(workspace).toContain('This is the semantic routing index')
    expect(workspace).toContain('choose the smallest workflow first')
    expect(workspace).toContain('extras.push(`Studio Run recipe:')
    expect(workspace).toContain('extras.push(`profile:')
    expect(longVideoDirector).toContain('Do not use this workflow when the selected built-in skill requires Studio Run')
    expect(agent).not.toContain('Do not activate a built-in skill or Studio Run because the request resembles its description')
  })

  it('preserves full audio tool capabilities with a native-audio exception for direct video', () => {
    const agent = read('src/lib/prompts/agent.md')
    const animate = read('src/lib/prompts/animate.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('Native-audio exception')
    expect(agent).toContain('single standalone audio-generation tool')
    expect(agent).toContain('put dialogue, narration, music, ambience, and SFX in `story_prompt`')
    expect(animate).toContain('this script is the complete audio direction for `generate_animation`')
    expect(animate).toContain('Never prepare this workflow with `generate_audio`')
    expect(agentTs).not.toContain('directVideoGenerationStarted')
    expect(agentTs).not.toContain('blockIndependentAudioAfterDirectVideo')
    expect(agentTs).toContain('single Agent-facing audio-generation tool')
    expect(agentTs).toContain('make exactly one model generation with kind="mixed"')
    expect(agentTs).not.toContain('ctx.userRequest')
    expect(agentTs).not.toContain('requestsImageConditionedAudio')
    expect(agentTs).not.toContain('validateAudioKindForRequest')
    expect(agentTs).toContain("conditioning: z.discriminatedUnion('type'")
    expect(agentTs).toContain('ctx.explicitMediaIndices.includes(imageMediaIndex)')
    expect(agentTs).toContain('selected Timeline state is never inherited')
    expect(agentTs).toContain('z.string().max(SEED_AUDIO_AGENT_PROMPT_MAX_CHARS)')
    expect(read('src/lib/prompts/audio.md')).toContain('Agent-authored `prompt` <= 1,250 characters')
    expect(agentTs).toContain('prompts/audio.md')
    expect(agentTs).toContain('reference_voices')
    expect(agentTs).toContain('sample_rate')
    expect(agentTs).toContain('requires verification of Seed Audio exact speech')
    expect(read('src/lib/prompts/audio.md')).toContain('call `transcribe_audio` on the returned public audio URL')
    expect(read('src/lib/prompts/audio.md')).toContain('call `generate_audio` exactly once with `kind: "mixed"`')
    expect(agentTs).toContain('Outside this exception, \\`generate_audio\\` retains its full standalone scope')
  })

  it('keeps SeeDance Fast as the default video model unless user or app selects another model', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('usually SeeDance 2.0 Fast')
    expect(agent).toContain('`seedance-fast`')
    expect(agentTs).toContain('resolveAgentVideoSelection')
    expect(agentTs).toContain('appAuto: (ctx as any).videoAuto')
    expect(agentTs).toContain('toolModel: model')
    expect(agentTs).toContain('toolResolution: video_resolution')
    expect(agentTs).toContain('Default model follows app selection, usually SeeDance 2.0 Fast')
    expect(agentTs).toContain('when the user asks for Seedance 2.5')
  })

  it('uses path-based composition patching instead of full currentDesign code injection', () => {
    const agentTs = read('src/lib/agent.ts')
    const coding = read('src/lib/prompts/agent-coding.md')
    const context = read('src/lib/agent-context.ts')

    expect(agentTs).toContain('[Current composition pointer]')
    expect(agentTs).toContain('currentDesignPath')
    expect(agentTs).toContain('code_path')
    expect(agentTs).not.toContain('[Current Remotion composition code')
    expect(agentTs).not.toContain('__lastDesignPayload = options.currentDesign')

    expect(coding).toContain('include that exact path as `code_path`')
    expect(coding).toContain('natural JS/TS/JSX/TSX Remotion module')
    expect(coding).toContain("return {\n  type: 'render'")
    expect(coding).toContain('Do not rely on implicit remembered composition code across turns')
    expect(context).toContain('[Current Composition]')
    expect(context).toContain('code_path')
    expect(context).not.toContain('[Current Design]')
  })

  it('routes long video work through the long-video-director skill before short video scripts', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')
    const skill = read('src/skills/long-video-director/SKILL.md')
    const anchor = read('src/skills/long-video-anchor/SKILL.md')
    const storyboard = read('src/skills/long-video-storyboard/SKILL.md')

    expect(agent).toContain('skills/long-video-director/SKILL.md')
    expect(agent).toContain('visual anchors')
    expect(agent).toContain('continue that workflow even when the latest user message does not repeat `[Active skill: long-video-director]`')
    expect(skill).toContain('You are the orchestrator and reviewer for long-video work')
    expect(skill).toContain('`skills/long-video-anchor/SKILL.md` for character, scene, and prop anchors')
    expect(skill).toContain('`skills/long-video-storyboard/SKILL.md` for one 6+ panel storyboard image per segment')
    expect(skill).toContain('`prompts/animate.md` for final segment scripts, preflight, and real video generation')
    expect(skill).toContain('Story direction approval')
    expect(skill).toContain('The next gate after segment-outline approval is **Gate 5: Director Beat Board**, not OpenAI storyboard generation')
    expect(agent).toContain('Do not jump straight to full scripts')
    expect(agent).toContain('do not use fenced code blocks')
    expect(skill).toContain('Do not dump a full long-video package in one response')

    expect(skill).toContain('Video models do **not** know what happened in the previous segment')
    expect(skill).toContain('Each video generation call can produce at most 15 seconds')
    expect(skill).toContain('Do not dump a full long-video package in one response')
    expect(skill).toContain('A gate is not passed just because text or an image was generated')
    expect(skill).toContain('Do not use fenced code blocks for seam overviews')
    expect(skill).toContain('`skills/long-video-anchor/SKILL.md` for character, scene, and prop anchors')
    expect(skill).toContain('`skills/long-video-storyboard/SKILL.md` for one 6+ panel storyboard image per segment')
    expect(skill).toContain('`prompts/animate.md` for final segment scripts, preflight, and real video generation')
    expect(skill).toContain('Do not bring up Remotion during this workflow')
    expect(skill).toContain('Timeline')
    expect(skill).toContain('CUI')
    expect(skill).toContain('Asset Inventory And Anchor Plan')
    expect(skill).toContain('Story Direction')
    expect(skill).toContain('offer 2-3 story directions')
    expect(skill).toContain('In the first response, do not generate assets, storyboard images, or `Shot N (Xs):` scripts')
    expect(skill).toContain('Segment Outline And Seam Plan')
    expect(skill).toContain('Director Beat Board')
    expect(skill).not.toContain('Write And Approve Director Beat Boards')
    expect(skill).toContain('Do not call `generate_image` for storyboard images yet')
    expect(skill).toContain('The next gate after segment-outline approval is **Gate 5: Director Beat Board**, not OpenAI storyboard generation')
    expect(skill).toContain('When presenting seams, use normal Markdown')
    expect(skill).toContain('The beat board must upgrade flat plot into direction')
    expect(skill).toContain('Use compact bullets only')
    expect(skill).toContain('Do not use Markdown tables, horizontal rules, ASCII diagrams')
    expect(skill).toContain('visual impact point')
    expect(skill).toContain('risk note')
    expect(skill).not.toContain('Final Preflight Before Submission')
    expect(skill).not.toContain('Do not write segment scripts before the anchor images are visible and approved')
    expect(skill).toContain('Read and follow `skills/long-video-anchor/SKILL.md`')
    expect(skill).toContain('Read and follow `skills/long-video-storyboard/SKILL.md`')
    expect(skill).toContain('Use `animate.md` for final segment scripts and preflight')
    expect(skill).toContain('Tool output can be "passed self-check" only; only the user can approve a gate')
    expect(skill).toContain('Never say anchors or storyboards are "approved" until the user explicitly confirms them')
    expect(skill).toContain('Do not enter Gate 4 until the user approves the reviewed anchors')
    expect(skill).toContain('Do not enter Gate 7 until the user approves the reviewed storyboards')
    expect(skill).toContain('beat board approved')
    expect(agentTs).toContain('active long-video-director workflow is generating director storyboard images')
    expect(read('src/lib/prompts/generate_image_tool.md')).toContain('director storyboard images required by `long-video-director`')
    expect(skill).toContain('review')
    expect(skill).toContain('every approved asset is referenced where needed')
    expect(skill).toContain('If a required storyboard or anchor ref is missing from the exact `story_prompt`, stop and rewrite')
    expect(skill).toContain('The video provider only receives media refs that are present in the final tool submission')
    expect(skill).toContain('exact refs per segment')
    expect(skill).toContain('Segment Outline And Seam Plan')
    expect(skill).toContain('Fewer segments are better for consistency')
    expect(skill).toContain('30s should usually be 2 x 15s')
    expect(anchor).toContain('reusable visual reference sheets')
    expect(anchor).toContain('stable visual facts')
    expect(anchor).toContain('Character card')
    expect(anchor).toContain('Scene card')
    expect(anchor).toContain('Prop card')
    expect(anchor).toContain('Label: CHARACTER: [neutral asset name]')
    expect(anchor).toContain('Label: SCENE: [neutral asset name]')
    expect(anchor).toContain('Label: PROP: [neutral asset name]')
    expect(skill).not.toContain('Chinese name')
    expect(skill).not.toContain('romanized name')
    expect(skill).not.toContain('State anchor template')
    expect(skill).not.toContain('Style anchor template')
    expect(skill).not.toContain('V character identity anchor')
    expect(anchor).toContain('front / side / back views')
    expect(anchor).not.toContain('referenceSheetType')
    expect(anchor).toContain('anchor image limit')
    expect(skill).toContain('Shot N (Xs):')
    expect(skill).not.toContain('total duration budget')
    expect(skill).not.toContain('Do not parallel-generate dependent anchors')
    expect(anchor).toContain('After every generated anchor, call `analyze_image`')
    expect(anchor).toContain("a user-provided character's hair, hat, clothing, face, age, body, or style family changed without approval")
    expect(anchor).toContain('scene card or prop card accidentally includes the principal character')
    expect(anchor).toContain('Preserve the source style family')
    expect(anchor).toContain('A 3D cartoon source must not become a flat 2D sheet')
    expect(anchor).toContain('All anchors in the same project must share the approved project style family')
    expect(anchor).toContain('Scene and prop cards must not drift into 2D illustration when the character anchor is 3D cartoon')
    expect(anchor).toContain('any scene or prop anchor drifts into a different render family')
    expect(anchor).toContain('Use "passed self-check" rather than "approved"')
    expect(storyboard).toContain('Generate exactly one storyboard image per segment with `generate_image` using `model: "openai"`')
    expect(storyboard).toContain('Always pass `aspectRatio` to `generate_image` using the approved target aspect ratio')
    expect(storyboard).toContain('Do not create one full-video storyboard sheet')
    expect(storyboard).toContain('Generate storyboards sequentially in segment order')
    expect(storyboard).toContain('Do not generate storyboard images in parallel')
    expect(storyboard).toContain('wait for its image, call `analyze_image`, and record the resulting media ref before starting the next segment')
    expect(storyboard).toContain('S1 panels must be labeled `S1-P1` to `S1-P6`; S2 panels must not appear in the S1 storyboard')
    expect(storyboard).toContain('Use the approved target aspect ratio for every storyboard sheet')
    expect(storyboard).toContain('Do not ask for visible PART dividers')
    expect(storyboard).toContain('Each segment storyboard must contain at least 6 shot panels')
    expect(storyboard).toContain('readable label strip with shot number, duration, framing, camera movement, and transition or seam note')
    expect(storyboard).toContain('Do not label panels with only `S1-P1`')
    expect(storyboard).toContain('Label strips are graphic overlays only')
    expect(storyboard).toContain('A correctly labeled storyboard is still a failure if the character identity or 3D cartoon render family drifts')
    expect(storyboard).toContain('If a principal character appears in the segment, pass that character anchor as `media_index`')
    expect(storyboard).toContain('reference_media_indices')
    expect(storyboard).toContain('After every generated storyboard image, call `analyze_image`')
    expect(storyboard).toContain('a required character changes hair, hat, clothing, face, age, body type, or style')
    expect(storyboard).toContain('a required 3D character becomes flat 2D')
    expect(storyboard).toContain("scene or prop rendering style conflicts with the approved character anchor's render family")
    expect(storyboard).toContain('labels are missing, unreadable, or only show panel IDs')
    expect(storyboard).toContain('the storyboard sheet uses the wrong aspect ratio')
    expect(storyboard).toContain('label overlays caused character or style drift')
    expect(storyboard).toContain('Use "passed self-check" rather than "approved"')
    expect(storyboard).toContain('regenerate only the failed segment(s)')
    expect(skill).toContain('prompts/animate.md')
    expect(anchor).toContain('name: anchor')
    expect(storyboard).toContain('name: storyboard')
    expect(skill).not.toContain('skills/video-ffmpeg-lab/SKILL.md')
    expect(skill).not.toContain('run_code')
    expect(skill).not.toContain('FFmpeg')
    expect(skill).not.toContain('Workspace Manifest')
  })

})
