import { describe, expect, it } from 'vitest'
import { readFileSync } from 'fs'
import path from 'path'

const root = path.resolve(__dirname, '..')

function read(rel: string) {
  return readFileSync(path.join(root, rel), 'utf8')
}

describe('agent prompt policy guards', () => {
  it('keeps image work on generate_image unless editable runtime is explicit', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('Default tool: `generate_image`')
    expect(agent).toContain('Static charts, infographics, posters, and marketing images go to `generate_image`')
    expect(agentTs).toContain('\\`runtime: "composition"\\`: Remotion/editable composition draft')
    expect(agentTs).toContain('\\`runtime: "design"\\` or omitted: legacy alias for \\`runtime: "composition"\\`')
    expect(agentTs).toContain('\\`runtime: "node"\\`: open backend Node with FFmpeg/FFprobe')
  })

  it('keeps preview_frame as one public tool with Remotion and FFmpeg engines', () => {
    const agentTs = read('src/lib/agent.ts')

    expect(agentTs).toContain('Remotion compositions are rendered with Remotion; raw uploaded/generated videos are extracted with FFmpeg')
    expect(agentTs).toContain('For raw video snapshots: use timestamp')
    expect(agentTs).toContain('When design_path is provided it is authoritative; media_index is ignored')
    expect(agentTs).toContain('const targetMediaIndex = design_path')
    expect(agentTs).toContain("source: 'video'")
    expect(agentTs).toContain("source: 'composition'")
    expect(agentTs).toContain('Render succeeded. Treat this as a successful preview_frame result')
    expect(agentTs).toContain('Continue with write_file when the user asked to publish')
    expect(agentTs).not.toContain('extract_video_frame: tool')
  })

  it('does not inject canned run_code narration into CUI messages', () => {
    const agentTs = read('src/lib/agent.ts')
    const en = read('src/lib/locales/en.ts')
    const zh = read('src/lib/locales/zh.ts')

    expect(agentTs).toContain("translate(responseLocale, 'agent.status.generatingCode')")
    expect(en).toContain("'agent.status.generatingCode': 'Generating code...'")
    expect(zh).toContain("'agent.status.generatingCode': '代码生成中...'")
    expect(agentTs).not.toContain('I am writing the Remotion code now')
    expect(agentTs).not.toContain('I am adjusting the code and checking the result')
    expect(agentTs).not.toContain('getRunCodeIntro')
  })

  it('keeps Remotion composition code in the local runtime shape', () => {
    const remotion = read('src/lib/prompts/remotion-composition.md')

    expect(remotion).toContain('Never write')
    expect(remotion).toContain('export default')
    expect(remotion).toContain('function Composition(props)')
    expect(remotion).toContain('Do not use ES module syntax')
  })

  it('returns resolved generate_image URLs for Remotion composition use', () => {
    const agentTs = read('src/lib/agent.ts')

    expect(agentTs).toContain('Resolved image URL:')
    expect(agentTs).toContain('Use this URL directly in Remotion composition props/code')
    expect(agentTs).toContain('do not use the <<<media_${mediaIndex}>>> marker inside composition code')
  })

  it('uses full timeline snapshots when materializing Remotion compositions', () => {
    const agentTs = read('src/lib/agent.ts')

    expect(agentTs).toContain("select('id, type, design_path')")
    expect(agentTs).toContain('const available = snaps?.length || 0')
    expect(agentTs).toContain('Invalid index ${input.media_index}. Available: 1-${available}.')
    expect(agentTs).toContain('not an editable Remotion composition')
  })

  it('returns resolved voiceover URLs for Remotion audio use', () => {
    const agentTs = read('src/lib/agent.ts')

    expect(agentTs).toContain('Resolved voiceover URL:')
    expect(agentTs).toContain('Use this URL directly in Remotion <Audio src>')
    expect(agentTs).toContain('marker inside composition code or props')
    expect(agentTs).toContain("deductCredits(ctx.userId, null, 'create_voiceover', result.tts.model)")
    expect(agentTs).toContain('[billing] generate_voiceover deduct error:')
  })

  it('surfaces generated audio progress and playable cards in CUI', () => {
    const agentTs = read('src/lib/agent.ts')
    const reconnect = read('src/hooks/useAgentRun.ts')
    const zh = read('src/lib/locales/zh.ts')

    expect(agentTs).toContain('formatGeneratedAudioForCui')
    expect(agentTs).toContain("translate(responseLocale, 'agent.status.generatingVoiceover')")
    expect(agentTs).toContain("translate(responseLocale, 'agent.status.generatingAudio')")
    expect(zh).toContain("'agent.status.generatingVoiceover': '生成配音中...'")
    expect(zh).toContain("'agent.status.generatingAudio': '生成音频中...'")
    expect(agentTs).toContain('formatMusicLine')
    expect(agentTs).toContain('music:${safeTrackIndex}|${title}|${safeDuration}|${tags}|${playUrl}|${finalUrl}')
    expect(agentTs).toContain('all new music generation routes go through Seed Audio')
    expect(agentTs).toContain("provider: z.enum(['auto', 'evolink-seed-audio'])")
    expect(agentTs).not.toContain('waitForPreview: true')
    expect(agentTs).not.toContain("provider=\"suno\"")
    expect(agentTs).not.toContain("provider: z.enum(['auto', 'evolink-seed-audio', 'suno'])")
    expect(agentTs).toContain('deductSeedAudioCredits')
    expect(agentTs).toContain('providerCreditsUsed: result.creditsUsed')
    expect(agentTs).not.toContain("deductCredits(ctx.userId ?? '', null, 'create_music')")
    expect(agentTs).toContain('const generatedAudioLine = formatGeneratedAudioForCui(toolName, toolOutput, responseLocale)')
    expect(reconnect).toContain("case 'music_task'")
    expect(reconnect).toContain('callbacks.onMusicTask?.')
  })

  it('keeps uploaded video auto-analysis in the tool-aware history path', () => {
    const editor = read('src/components/Editor.tsx')
    const agentRoute = read('src/app/api/agent/route.ts')

    expect(editor).toContain('First call analyze_video with media_index')
    expect(editor).toContain('First call analyze_video for each uploaded video media_index')
    expect(editor).toContain("analyze_video's result is persisted in agent_tool_history")
    expect(editor).not.toContain("handleAgentRequest('', undefined, undefined, { silent: true, uploadedVideoCount")
    expect(agentRoute).toContain('const isNormalMode = !tipsTeaser && !nameProject && !previewsReady && !tipReaction && !analysisOnly')
  })

  it('runs a trusted Skill template through the final result while preserving ordinary confirmation', () => {
    const agent = read('src/lib/prompts/agent.md')
    const animate = read('src/lib/prompts/animate.md')
    const agentTs = read('src/lib/agent.ts')
    const executionRunner = read('src/lib/agent-execution-runner.ts')

    expect(agent).toContain('Only call `generate_animation` after the user confirms a visible script')
    expect(animate).toContain('in an ordinary CUI/editor request, write the complete visible script and wait for confirmation')
    expect(animate).toContain('the system prompt explicitly supplies a `Trusted Skill template launch`')
    expect(agentTs).toContain('trusted Skill template launch exception')
    expect(agentTs).toContain("translate(responseLocale, 'status.submittingVideo')")
    expect(agentTs).toContain("code: 'skill_video_submission_pending'")
    expect(agentTs).toContain("assessment.code === 'skill_video_submission_pending'")
    expect(agentTs).toContain('Call generate_animation now with that exact complete script')
    expect(executionRunner).toContain("input.terminal?.code === 'skill_video_submission_pending'")
    expect(executionRunner).toContain('Do not rewrite it or ask for confirmation. Call generate_animation now')
  })

  it('reconnects text-only CUI projects before the first snapshot exists', () => {
    const editor = read('src/components/Editor.tsx')

    expect(editor).toContain('enabled: !!projectId && !inactive')
    expect(editor).not.toContain('enabled: !!projectId && (initialSnapshots?.length ?? 0) > 0')
  })

  it('keeps built-in image skill triggers visible before the image guide is read', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')
    const tool = read('src/lib/prompts/generate_image_tool.md')
    const image = read('src/lib/prompts/image.md')

    expect(agent).toContain('prompts/enhance.md')
    expect(agent).toContain('skill: "enhance"')
    expect(agent).toContain('prompts/creative.md')
    expect(agent).toContain('skill: "creative"')
    expect(agent).toContain('prompts/wild.md')
    expect(agent).toContain('skill: "wild"')
    expect(agent).toContain('prompts/captions.md')
    expect(agent).toContain('skill: "captions"')

    expect(tool).toContain('read only that one skill prompt file once')
    expect(tool).toContain('Do not read `prompts/image.md` just to route the skill')
    expect(tool).not.toContain('prompts/enhance.md')
    expect(image).toContain('backend no longer injects the full template automatically')
    expect(agentTs).not.toContain('template rules are auto-injected')
    expect(agentTs).toContain('you must have read and internalized that skill prompt once')
  })

  it('requires script confirmation before video provider submission unless direct-submit is explicit', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('video rendering has a script review gate unless the user explicitly asks to submit/render without confirmation')
    expect(agent).toContain('Only call `generate_animation` after the user confirms')
    expect(agent).toContain('Direct-submit exception')
    expect(agent).toContain('直接提交渲染')
    expect(agent).toContain('不要问我确认')
    expect(agent).not.toContain('Do not add a review loop')
    expect(agent).not.toContain('even if the user says "直接提交" or "不要确认"')

    expect(agentTs).toContain('explicitly authorizes direct submission without confirmation')
    expect(agentTs).toContain('直接提交渲染')
  })

  it('treats invalid Seedance reference images as terminal input errors', () => {
    const agent = read('src/lib/prompts/agent.md')
    const animate = read('src/lib/prompts/animate.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain("read_file('prompts/animate.md')")
    expect(animate).toContain('width and height each 300-6000px')
    expect(animate).toContain('`too_small`, `too_large`')
    expect(animate).toContain('`retryable: false` means do not resubmit the same URL')
    expect(animate).toContain('A second unchanged submission becomes `terminal: true`')
    expect(agentTs).toContain('If repairable=true, decide whether to prepare a new compliant image URL')
  })

  it('keeps single video generation in the model duration range and routes longer requests to the director skill', () => {
    const agent = read('src/lib/prompts/agent.md')
    const animate = read('src/lib/prompts/animate.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('Hard duration range: a single SeeDance script/call must be 4-15s; Kling is 5-15s')
    expect(agent).toContain('If requested/source duration is shorter than the model minimum, use the minimum')
    expect(agent).toContain('If output is longer than the selected model max, use `skills/long-video-director/SKILL.md`')
    expect(agent).toContain('Single-script rule: if a complete approved script is <=15s')
    expect(agent).toContain('Do not submit only one shot or split just because it has multiple shot lines')
    expect(agent).toContain('Long source video rule: if an existing timeline/reference video is >15s')
    expect(agent).toContain('do not compress the whole source into one short edit')
    expect(agent).toContain('Reference video input limit: one SeeDance generation may use up to 15s combined source/reference video duration')
    expect(agent).toContain('dimensions 300-6000px')
    expect(agent).toContain('409,600-2,086,876 frame pixels')
    expect(agent).toContain('Kling accepts one .mp4/.mov, <=200MB, <=2K')
    expect(agent).toContain('keep the output duration aligned with the combined source duration shown in Media Index')
    expect(agent).toContain('clamp it to the SeeDance model range: minimum 4s, maximum 15s')

    expect(animate).toContain('Every normal SeeDance script sent to a video generation model must be **4 to 15 seconds**')
    expect(animate).toContain("SeeDance's minimum output duration is 4 seconds")
    expect(animate).toContain('keep it as **one video generation script**')
    expect(animate).toContain('If the script totals less than 4s, extend it to a compact 4s script instead of submitting a shorter duration')
    expect(animate).toContain('The whole title + every `Shot N (Xs):` line + `Style:` line must be submitted together')
    expect(animate).toContain('Do not submit only a single shot or a single line from the script')
    expect(animate).toContain('Multiple shots are normal inside one 15s video')
    expect(animate).toContain('do **not** write one long script')
    expect(animate).toContain('If the source/reference video itself is longer than 15s')
    expect(animate).toContain('For longer source videos, use the long-video-director workflow instead of one short compressed edit')
    expect(animate).toContain('their **combined source duration must be 15 seconds or less** for a single SeeDance generation')
    expect(animate).toContain('This is an input limit, not a creative long-video workflow')
    expect(animate).toContain('frame pixels width*height between 409,600 and 2,086,876')
    expect(animate).toContain('Kling docs do not state a video resolution lower bound')
    expect(animate).toContain('Never write or submit a SeeDance generated video duration below 4s')

    expect(agentTs).toContain('SeeDance/SeeDance Mini is 4-15 seconds')
    expect(agentTs).toContain('4s minimum output, 5s default/common preset')
    expect(agentTs).toContain('Kling is 5-15 seconds')
    expect(agentTs).toContain('set \\`duration: 4\\`')
    expect(agentTs).toContain('If a complete script totals 15 seconds or less, submit it as one video generation call')
    expect(agentTs).toContain('Put the whole title, every \\`Shot N (Xs):\\` line, and the \\`Style:\\` line into the same \\`story_prompt\\`')
    expect(agentTs).toContain('Do not submit only one shot, the first shot, or one line from the script')
    expect(agentTs).toContain('Total duration must be 15 seconds or less')
    expect(agentTs).toContain('Long source video rule')
    expect(agentTs).toContain('if a timeline/reference video is longer than 15 seconds')
    expect(agentTs).toContain('the combined source duration of all timeline/uploaded/reference videos used in the script must be 15 seconds or less')
    expect(agentTs).toContain('frame pixels width*height between 409,600 and 2,086,876')
    expect(agentTs).toContain('Kling video references must be <=200MB and <=2K; no explicit lower resolution is documented')
    expect(agentTs).toContain('set this to the combined source video duration from Media Index clamped to the selected model range')
    expect(agentTs).not.toContain('Duration in seconds: 3, 5, 7, 10, or 15')
    expect(agentTs).not.toContain("The model's minimum generation duration is 5 seconds")
  })

  it('keeps explicit explainer videos on editable Studio Run before provider duration routing', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')
    const longVideoDirector = read('src/skills/long-video-director/SKILL.md')

    expect(agent).toContain('Explicit explainer, Studio Run, Remotion, or matched built-in Composition requests')
    expect(agent).toContain('Do not reinterpret a 30s/60s Composition as provider clips')
    expect(agentTs).toContain('This provider limit does not reroute an explicit explainer-video')
    expect(longVideoDirector).toContain('Do not use for explainer-video, Studio Run, Remotion')
  })

  it('keeps SeeDance Fast as the default video model unless user or app selects another model', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('usually SeeDance 2.0 Fast')
    expect(agent).toContain('`seedance-fast`')
    expect(agentTs).toContain('resolveAgentVideoSelection')
    expect(agentTs).toContain('appAuto: (ctx as any).videoAuto')
    expect(agentTs).toContain('toolModel: model')
    expect(agentTs).toContain('toolResolution: video_resolution')
    expect(agentTs).toContain('Default follows the app selection (usually seedance-fast)')
  })

  it('uses path-based composition patching instead of full currentDesign code injection', () => {
    const agentTs = read('src/lib/agent.ts')
    const coding = read('src/lib/prompts/agent-coding.md')
    const context = read('src/lib/agent-context.ts')

    expect(agentTs).toContain('[Current composition pointer]')
    expect(agentTs).toContain('currentDesignPath')
    expect(agentTs).toContain('code_path')
    expect(agentTs).not.toContain('[Current Remotion composition code')
    expect(agentTs).not.toContain('__lastDesignPayload = options.currentDesign')

    expect(coding).toContain('include that exact path as `code_path`')
    expect(coding).toContain('natural JS/TS/JSX/TSX Remotion module')
    expect(coding).toContain("return {\n  type: 'render'")
    expect(coding).toContain('Do not rely on implicit remembered composition code across turns')
    expect(context).toContain('[Current Composition]')
    expect(context).toContain('code_path')
    expect(context).not.toContain('[Current Design]')
  })

  it('routes long video work through the long-video-director skill before short video scripts', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')
    const skill = read('src/skills/long-video-director/SKILL.md')
    const anchor = read('src/skills/long-video-anchor/SKILL.md')
    const storyboard = read('src/skills/long-video-storyboard/SKILL.md')

    expect(agent).toContain('skills/long-video-director/SKILL.md')
    expect(agent).toContain('visual anchors')
    expect(agent).toContain('continue that workflow even when the latest user message does not repeat `[Active skill: long-video-director]`')
    expect(skill).toContain('You are the orchestrator and reviewer for long-video work')
    expect(skill).toContain('`skills/long-video-anchor/SKILL.md` for character, scene, and prop anchors')
    expect(skill).toContain('`skills/long-video-storyboard/SKILL.md` for one 6+ panel storyboard image per segment')
    expect(skill).toContain('`prompts/animate.md` for final segment scripts, preflight, and real video generation')
    expect(skill).toContain('Story direction approval')
    expect(skill).toContain('The next gate after segment-outline approval is **Gate 5: Director Beat Board**, not OpenAI storyboard generation')
    expect(agent).toContain('Do not jump straight to full scripts')
    expect(agent).toContain('do not use fenced code blocks')
    expect(skill).toContain('Do not dump a full long-video package in one response')

    expect(skill).toContain('Video models do **not** know what happened in the previous segment')
    expect(skill).toContain('Each video generation call can produce at most 15 seconds')
    expect(skill).toContain('Do not dump a full long-video package in one response')
    expect(skill).toContain('A gate is not passed just because text or an image was generated')
    expect(skill).toContain('Do not use fenced code blocks for seam overviews')
    expect(skill).toContain('`skills/long-video-anchor/SKILL.md` for character, scene, and prop anchors')
    expect(skill).toContain('`skills/long-video-storyboard/SKILL.md` for one 6+ panel storyboard image per segment')
    expect(skill).toContain('`prompts/animate.md` for final segment scripts, preflight, and real video generation')
    expect(skill).toContain('Do not bring up Remotion during this workflow')
    expect(skill).toContain('Timeline')
    expect(skill).toContain('CUI')
    expect(skill).toContain('Asset Inventory And Anchor Plan')
    expect(skill).toContain('Story Direction')
    expect(skill).toContain('offer 2-3 story directions')
    expect(skill).toContain('In the first response, do not generate assets, storyboard images, or `Shot N (Xs):` scripts')
    expect(skill).toContain('Segment Outline And Seam Plan')
    expect(skill).toContain('Director Beat Board')
    expect(skill).not.toContain('Write And Approve Director Beat Boards')
    expect(skill).toContain('Do not call `generate_image` for storyboard images yet')
    expect(skill).toContain('The next gate after segment-outline approval is **Gate 5: Director Beat Board**, not OpenAI storyboard generation')
    expect(skill).toContain('When presenting seams, use normal Markdown')
    expect(skill).toContain('The beat board must upgrade flat plot into direction')
    expect(skill).toContain('Use compact bullets only')
    expect(skill).toContain('Do not use Markdown tables, horizontal rules, ASCII diagrams')
    expect(skill).toContain('visual impact point')
    expect(skill).toContain('risk note')
    expect(skill).not.toContain('Final Preflight Before Submission')
    expect(skill).not.toContain('Do not write segment scripts before the anchor images are visible and approved')
    expect(skill).toContain('Read and follow `skills/long-video-anchor/SKILL.md`')
    expect(skill).toContain('Read and follow `skills/long-video-storyboard/SKILL.md`')
    expect(skill).toContain('Use `animate.md` for final segment scripts and preflight')
    expect(skill).toContain('Tool output can be "passed self-check" only; only the user can approve a gate')
    expect(skill).toContain('Never say anchors or storyboards are "approved" until the user explicitly confirms them')
    expect(skill).toContain('Do not enter Gate 4 until the user approves the reviewed anchors')
    expect(skill).toContain('Do not enter Gate 7 until the user approves the reviewed storyboards')
    expect(skill).toContain('beat board approved')
    expect(agentTs).toContain('active long-video-director workflow is generating director storyboard images')
    expect(read('src/lib/prompts/generate_image_tool.md')).toContain('director storyboard images required by `long-video-director`')
    expect(skill).toContain('review')
    expect(skill).toContain('every approved asset is referenced where needed')
    expect(skill).toContain('If a required storyboard or anchor ref is missing from the exact `story_prompt`, stop and rewrite')
    expect(skill).toContain('The video provider only receives media refs that are present in the final tool submission')
    expect(skill).toContain('exact refs per segment')
    expect(skill).toContain('Segment Outline And Seam Plan')
    expect(skill).toContain('Fewer segments are better for consistency')
    expect(skill).toContain('30s should usually be 2 x 15s')
    expect(anchor).toContain('reusable visual reference sheets')
    expect(anchor).toContain('stable visual facts')
    expect(anchor).toContain('Character card')
    expect(anchor).toContain('Scene card')
    expect(anchor).toContain('Prop card')
    expect(anchor).toContain('Label: CHARACTER: [neutral asset name]')
    expect(anchor).toContain('Label: SCENE: [neutral asset name]')
    expect(anchor).toContain('Label: PROP: [neutral asset name]')
    expect(skill).not.toContain('Chinese name')
    expect(skill).not.toContain('romanized name')
    expect(skill).not.toContain('State anchor template')
    expect(skill).not.toContain('Style anchor template')
    expect(skill).not.toContain('V character identity anchor')
    expect(anchor).toContain('front / side / back views')
    expect(anchor).not.toContain('referenceSheetType')
    expect(anchor).toContain('anchor image limit')
    expect(skill).toContain('Shot N (Xs):')
    expect(skill).not.toContain('total duration budget')
    expect(skill).not.toContain('Do not parallel-generate dependent anchors')
    expect(anchor).toContain('After every generated anchor, call `analyze_image`')
    expect(anchor).toContain("a user-provided character's hair, hat, clothing, face, age, body, or style family changed without approval")
    expect(anchor).toContain('scene card or prop card accidentally includes the principal character')
    expect(anchor).toContain('Preserve the source style family')
    expect(anchor).toContain('A 3D cartoon source must not become a flat 2D sheet')
    expect(anchor).toContain('All anchors in the same project must share the approved project style family')
    expect(anchor).toContain('Scene and prop cards must not drift into 2D illustration when the character anchor is 3D cartoon')
    expect(anchor).toContain('any scene or prop anchor drifts into a different render family')
    expect(anchor).toContain('Use "passed self-check" rather than "approved"')
    expect(storyboard).toContain('Generate exactly one storyboard image per segment with `generate_image` using `model: "openai"`')
    expect(storyboard).toContain('Always pass `aspectRatio` to `generate_image` using the approved target aspect ratio')
    expect(storyboard).toContain('Do not create one full-video storyboard sheet')
    expect(storyboard).toContain('Generate storyboards sequentially in segment order')
    expect(storyboard).toContain('Do not generate storyboard images in parallel')
    expect(storyboard).toContain('wait for its image, call `analyze_image`, and record the resulting media ref before starting the next segment')
    expect(storyboard).toContain('S1 panels must be labeled `S1-P1` to `S1-P6`; S2 panels must not appear in the S1 storyboard')
    expect(storyboard).toContain('Use the approved target aspect ratio for every storyboard sheet')
    expect(storyboard).toContain('Do not ask for visible PART dividers')
    expect(storyboard).toContain('Each segment storyboard must contain at least 6 shot panels')
    expect(storyboard).toContain('readable label strip with shot number, duration, framing, camera movement, and transition or seam note')
    expect(storyboard).toContain('Do not label panels with only `S1-P1`')
    expect(storyboard).toContain('Label strips are graphic overlays only')
    expect(storyboard).toContain('A correctly labeled storyboard is still a failure if the character identity or 3D cartoon render family drifts')
    expect(storyboard).toContain('If a principal character appears in the segment, pass that character anchor as `media_index`')
    expect(storyboard).toContain('reference_media_indices')
    expect(storyboard).toContain('After every generated storyboard image, call `analyze_image`')
    expect(storyboard).toContain('a required character changes hair, hat, clothing, face, age, body type, or style')
    expect(storyboard).toContain('a required 3D character becomes flat 2D')
    expect(storyboard).toContain("scene or prop rendering style conflicts with the approved character anchor's render family")
    expect(storyboard).toContain('labels are missing, unreadable, or only show panel IDs')
    expect(storyboard).toContain('the storyboard sheet uses the wrong aspect ratio')
    expect(storyboard).toContain('label overlays caused character or style drift')
    expect(storyboard).toContain('Use "passed self-check" rather than "approved"')
    expect(storyboard).toContain('regenerate only the failed segment(s)')
    expect(skill).toContain('prompts/animate.md')
    expect(anchor).toContain('name: anchor')
    expect(storyboard).toContain('name: storyboard')
    expect(skill).not.toContain('skills/video-ffmpeg-lab/SKILL.md')
    expect(skill).not.toContain('run_code')
    expect(skill).not.toContain('FFmpeg')
    expect(skill).not.toContain('Workspace Manifest')
  })

})
