import { describe, expect, it } from 'vitest'
import { readFileSync } from 'fs'
import path from 'path'

const root = path.resolve(__dirname, '..')

function read(rel: string) {
  return readFileSync(path.join(root, rel), 'utf8')
}

describe('agent prompt policy guards', () => {
  it('keeps image work on generate_image unless editable runtime is explicit', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('Default tool: `generate_image`')
    expect(agent).toContain('Static charts, infographics, posters, and marketing images go to `generate_image`')
    expect(agentTs).toContain('Use ONLY for video/animation or when user explicitly requests an editable template')
  })

  it('keeps built-in image skill triggers visible before the image guide is read', () => {
    const agent = read('src/lib/prompts/agent.md')
    const tool = read('src/lib/prompts/generate_image_tool.md')
    const image = read('src/lib/prompts/image.md')

    expect(agent).toContain('prompts/enhance.md')
    expect(agent).toContain('skill: "enhance"')
    expect(agent).toContain('prompts/creative.md')
    expect(agent).toContain('skill: "creative"')
    expect(agent).toContain('prompts/wild.md')
    expect(agent).toContain('skill: "wild"')
    expect(agent).toContain('prompts/captions.md')
    expect(agent).toContain('skill: "captions"')

    expect(tool).toContain('read only that one skill prompt file once')
    expect(tool).toContain('Do not read `prompts/image.md` just to route the skill')
    expect(tool).not.toContain('prompts/enhance.md')
    expect(image).toContain('backend no longer injects the full template automatically')
  })

  it('requires script confirmation before video provider submission unless direct-submit is explicit', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('video rendering has a script review gate unless the user explicitly asks to submit/render without confirmation')
    expect(agent).toContain('Only call `generate_animation` after the user confirms')
    expect(agent).toContain('Direct-submit exception')
    expect(agent).toContain('直接提交渲染')
    expect(agent).toContain('不要问我确认')
    expect(agent).not.toContain('Do not add a review loop')
    expect(agent).not.toContain('even if the user says "直接提交" or "不要确认"')

    expect(agentTs).toContain('explicitly authorizes direct submission without confirmation')
    expect(agentTs).toContain('直接提交渲染')
  })

  it('keeps single video generation capped at 15s and routes longer requests to the director skill', () => {
    const agent = read('src/lib/prompts/agent.md')
    const animate = read('src/lib/prompts/animate.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('a single video-generation script/call must be 15 seconds or less')
    expect(agent).toContain('if the user provides or approves a complete video script whose total duration is 15 seconds or less')
    expect(agent).toContain('Put the entire title + all `Shot N (Xs):` lines + `Style:` line into the same `story_prompt`')
    expect(agent).toContain('Do not submit only one shot, the first shot, or one line from the script')
    expect(agent).toContain('Do not split it just because it contains multiple `Shot N (Xs):` lines')
    expect(agent).toContain('If the user asks for 30s')
    expect(agent).toContain('Use `skills/long-video-director/SKILL.md`')
    expect(agent).toContain('[Active skill: long-video-director]')
    expect(agent).toContain('if an existing timeline/reference video is longer than 15 seconds')
    expect(agent).toContain('do not compress the whole source into one 5s or 15s edit')
    expect(agent).toContain('add together the durations of all uploaded/timeline/reference videos')
    expect(agent).toContain('The combined source duration must be 15 seconds or less')
    expect(agent).toContain('keep the output duration aligned with the combined source duration shown in Media Index')

    expect(animate).toContain('Every normal script sent to a video generation model must be **15 seconds or less**')
    expect(animate).toContain('keep it as **one video generation script**')
    expect(animate).toContain('The whole title + every `Shot N (Xs):` line + `Style:` line must be submitted together')
    expect(animate).toContain('Do not submit only a single shot or a single line from the script')
    expect(animate).toContain('Multiple shots are normal inside one 15s video')
    expect(animate).toContain('do **not** write one long script')
    expect(animate).toContain('If the source/reference video itself is longer than 15s')
    expect(animate).toContain('For longer source videos, use the long-video-director workflow instead of one short compressed edit')
    expect(animate).toContain('their **combined source duration must be 15 seconds or less** for a single SeeDance generation')
    expect(animate).toContain('This is an input limit, not a creative long-video workflow')

    expect(agentTs).toContain('Single-call total duration: 5-15 seconds')
    expect(agentTs).toContain('If a complete script totals 15 seconds or less, submit it as one video generation call')
    expect(agentTs).toContain('Put the whole title, every \\`Shot N (Xs):\\` line, and the \\`Style:\\` line into the same \\`story_prompt\\`')
    expect(agentTs).toContain('Do not submit only one shot, the first shot, or one line from the script')
    expect(agentTs).toContain('Total duration must be 15 seconds or less')
    expect(agentTs).toContain('Long source video rule')
    expect(agentTs).toContain('if a timeline/reference video is longer than 15 seconds')
    expect(agentTs).toContain('the combined source duration of all timeline/uploaded/reference videos used in the script must be 15 seconds or less')
    expect(agentTs).toContain('set this to the combined source video duration from Media Index')
  })

  it('keeps Seedance as the default video model unless user or app selects Kling', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')

    expect(agent).toContain('usually SeeDance')
    expect(agent).toContain('prefer Kling')
    expect(agentTs).toContain("ctx.videoModel || 'seedance'")
    expect(agentTs).toContain('Default: seedance')
  })

  it('routes long video work through the long-video-director skill before short video scripts', () => {
    const agent = read('src/lib/prompts/agent.md')
    const agentTs = read('src/lib/agent.ts')
    const skill = read('src/skills/long-video-director/SKILL.md')
    const anchor = read('src/skills/long-video-anchor/SKILL.md')
    const storyboard = read('src/skills/long-video-storyboard/SKILL.md')

    expect(agent).toContain('skills/long-video-director/SKILL.md')
    expect(agent).toContain('visual anchors')
    expect(agent).toContain('continue that workflow even when the latest user message does not repeat `[Active skill: long-video-director]`')
    expect(agent).toContain('`long-video-director` is orchestration and review only')
    expect(agent).toContain('routes anchor work to `skills/long-video-anchor/SKILL.md`')
    expect(agent).toContain('storyboard work to `skills/long-video-storyboard/SKILL.md`')
    expect(agent).toContain('final scripts/preflight to `prompts/animate.md`')
    expect(agent).toContain('discuss and approve the story first')
    expect(agent).toContain('After segment-outline approval, the next gate is director beat board, not storyboard generation')
    expect(agent).toContain('Do not use fenced code blocks for long-video review content')
    expect(agent).toContain('Do not jump straight from an initial long-video request to full segment scripts')
    expect(agent).toContain('Do not dump the whole long-video package in one response')

    expect(skill).toContain('Video models do **not** know what happened in the previous segment')
    expect(skill).toContain('Each video generation call can produce at most 15 seconds')
    expect(skill).toContain('Do not dump a full long-video package in one response')
    expect(skill).toContain('A gate is not passed just because text or an image was generated')
    expect(skill).toContain('Do not use fenced code blocks for seam overviews')
    expect(skill).toContain('`skills/long-video-anchor/SKILL.md` for character, scene, and prop anchors')
    expect(skill).toContain('`skills/long-video-storyboard/SKILL.md` for one 6+ panel storyboard image per segment')
    expect(skill).toContain('`prompts/animate.md` for final segment scripts, preflight, and real video generation')
    expect(agent).toContain('then generate and inspect one OpenAI storyboard image for each segment')
    expect(agent).toContain('Do not bring up Remotion during the long-video workflow')
    expect(skill).toContain('Timeline')
    expect(skill).toContain('CUI')
    expect(skill).toContain('Asset Inventory And Anchor Plan')
    expect(skill).toContain('Story Direction')
    expect(skill).toContain('offer 2-3 story directions')
    expect(skill).toContain('In the first response, do not generate assets, storyboard images, or `Shot N (Xs):` scripts')
    expect(skill).toContain('Segment Outline And Seam Plan')
    expect(skill).toContain('Director Beat Board')
    expect(skill).not.toContain('Write And Approve Director Beat Boards')
    expect(skill).toContain('Do not call `generate_image` for storyboard images yet')
    expect(skill).toContain('The next gate after segment-outline approval is **Gate 5: Director Beat Board**, not OpenAI storyboard generation')
    expect(skill).toContain('When presenting seams, use normal Markdown')
    expect(skill).toContain('The beat board must upgrade flat plot into direction')
    expect(skill).toContain('Use compact bullets only')
    expect(skill).toContain('Do not use Markdown tables, horizontal rules, ASCII diagrams')
    expect(skill).toContain('visual impact point')
    expect(skill).toContain('risk note')
    expect(skill).not.toContain('Final Preflight Before Submission')
    expect(skill).not.toContain('Do not write segment scripts before the anchor images are visible and approved')
    expect(skill).toContain('Read and follow `skills/long-video-anchor/SKILL.md`')
    expect(skill).toContain('Read and follow `skills/long-video-storyboard/SKILL.md`')
    expect(skill).toContain('Use `animate.md` for final segment scripts and preflight')
    expect(skill).toContain('Tool output can be "passed self-check" only; only the user can approve a gate')
    expect(skill).toContain('Never say anchors or storyboards are "approved" until the user explicitly confirms them')
    expect(skill).toContain('Do not enter Gate 4 until the user approves the reviewed anchors')
    expect(skill).toContain('Do not enter Gate 7 until the user approves the reviewed storyboards')
    expect(skill).toContain('beat board approved')
    expect(agentTs).toContain('active long-video-director workflow is generating director storyboard images')
    expect(read('src/lib/prompts/generate_image_tool.md')).toContain('director storyboard images required by `long-video-director`')
    expect(skill).toContain('review')
    expect(skill).toContain('every approved asset is referenced where needed')
    expect(skill).toContain('exact refs per segment')
    expect(skill).toContain('Segment Outline And Seam Plan')
    expect(skill).toContain('Fewer segments are better for consistency')
    expect(skill).toContain('30s should usually be 2 x 15s')
    expect(anchor).toContain('reusable visual reference sheets')
    expect(anchor).toContain('stable visual facts')
    expect(anchor).toContain('Character card')
    expect(anchor).toContain('Scene card')
    expect(anchor).toContain('Prop card')
    expect(anchor).toContain('Label: CHARACTER: [neutral asset name]')
    expect(anchor).toContain('Label: SCENE: [neutral asset name]')
    expect(anchor).toContain('Label: PROP: [neutral asset name]')
    expect(skill).not.toContain('Chinese name')
    expect(skill).not.toContain('romanized name')
    expect(skill).not.toContain('State anchor template')
    expect(skill).not.toContain('Style anchor template')
    expect(skill).not.toContain('V character identity anchor')
    expect(anchor).toContain('front / side / back views')
    expect(anchor).not.toContain('referenceSheetType')
    expect(anchor).toContain('anchor image limit')
    expect(skill).toContain('Shot N (Xs):')
    expect(skill).not.toContain('total duration budget')
    expect(skill).not.toContain('Do not parallel-generate dependent anchors')
    expect(anchor).toContain('After every generated anchor, call `analyze_image`')
    expect(anchor).toContain("a user-provided character's hair, hat, clothing, face, age, body, or style family changed without approval")
    expect(anchor).toContain('scene card or prop card accidentally includes the principal character')
    expect(anchor).toContain('Preserve the source style family')
    expect(anchor).toContain('A 3D cartoon source must not become a flat 2D sheet')
    expect(anchor).toContain('All anchors in the same project must share the approved project style family')
    expect(anchor).toContain('Scene and prop cards must not drift into 2D illustration when the character anchor is 3D cartoon')
    expect(anchor).toContain('any scene or prop anchor drifts into a different render family')
    expect(anchor).toContain('Use "passed self-check" rather than "approved"')
    expect(storyboard).toContain('Generate exactly one storyboard image per segment with `generate_image` using `model: "openai"`')
    expect(storyboard).toContain('Always pass `aspectRatio` to `generate_image` using the approved target aspect ratio')
    expect(storyboard).toContain('Do not create one full-video storyboard sheet')
    expect(storyboard).toContain('Generate storyboards sequentially in segment order')
    expect(storyboard).toContain('Do not generate storyboard images in parallel')
    expect(storyboard).toContain('wait for its image, call `analyze_image`, and record the resulting media ref before starting the next segment')
    expect(storyboard).toContain('S1 panels must be labeled `S1-P1` to `S1-P6`; S2 panels must not appear in the S1 storyboard')
    expect(storyboard).toContain('Use the approved target aspect ratio for every storyboard sheet')
    expect(storyboard).toContain('Do not ask for visible PART dividers')
    expect(storyboard).toContain('Each segment storyboard must contain at least 6 shot panels')
    expect(storyboard).toContain('readable label strip with shot number, duration, framing, camera movement, and transition or seam note')
    expect(storyboard).toContain('Do not label panels with only `S1-P1`')
    expect(storyboard).toContain('Label strips are graphic overlays only')
    expect(storyboard).toContain('A correctly labeled storyboard is still a failure if the character identity or 3D cartoon render family drifts')
    expect(storyboard).toContain('If a principal character appears in the segment, pass that character anchor as `media_index`')
    expect(storyboard).toContain('reference_media_indices')
    expect(storyboard).toContain('After every generated storyboard image, call `analyze_image`')
    expect(storyboard).toContain('a required character changes hair, hat, clothing, face, age, body type, or style')
    expect(storyboard).toContain('a required 3D character becomes flat 2D')
    expect(storyboard).toContain("scene or prop rendering style conflicts with the approved character anchor's render family")
    expect(storyboard).toContain('labels are missing, unreadable, or only show panel IDs')
    expect(storyboard).toContain('the storyboard sheet uses the wrong aspect ratio')
    expect(storyboard).toContain('label overlays caused character or style drift')
    expect(storyboard).toContain('Use "passed self-check" rather than "approved"')
    expect(storyboard).toContain('regenerate only the failed segment(s)')
    expect(skill).toContain('prompts/animate.md')
    expect(anchor).toContain('name: anchor')
    expect(storyboard).toContain('name: storyboard')
    expect(skill).not.toContain('skills/video-ffmpeg-lab/SKILL.md')
    expect(skill).not.toContain('run_code')
    expect(skill).not.toContain('FFmpeg')
    expect(skill).not.toContain('Workspace Manifest')
  })

})
