import { describe, expect, it } from 'vitest'
import { readFileSync } from 'fs'
import path from 'path'
import { parseSkillMd } from '../src/lib/skill-registry'
import { getSkillManifest } from '../src/lib/workspace'

const root = path.resolve(__dirname, '..')

function read(rel: string) {
  return readFileSync(path.join(root, rel), 'utf8')
}

describe('Explainer Video built-in skill', () => {
  it('is exposed as a semantic route with its Studio workflow metadata', async () => {
    const manifest = await getSkillManifest()

    expect(manifest).toContain('This is the semantic routing index')
    expect(manifest).toContain('**explainer-video**')
    expect(manifest).toContain('Studio Run recipe: explainer-video')
    expect(manifest).toContain('profile: generated-explainer')
  })

  it('uses the current Remotion composition architecture', () => {
    const agent = read('src/lib/prompts/agent.md')
    const compositionPrompt = read('src/lib/prompts/remotion-composition.md')
    const rawSkill = read('src/skills/explainer-video/SKILL.md')
    const skill = parseSkillMd(rawSkill)

    expect(skill?.name).toBe('explainer-video')
    expect(skill?.makaron.studioRunRecipe).toBe('explainer-video')
    expect(skill?.makaron.studioRunProfile).toBe('generated-explainer')
    expect(skill?.makaron.builtIn).toBe(true)
    expect(skill?.makaron.tags).toContain('explainer')
    expect(skill?.allowedTools).toEqual(expect.arrayContaining([
      'read_file',
      'studio_run',
      'prepare_visual_asset',
      'run_code',
      'write_file',
      'preview_frame',
      'materialize_media',
      'transcribe_audio',
      'generate_audio',
      'generate_image',
    ]))

    expect(rawSkill).toContain('local Remotion composition workflow')
    expect(rawSkill).toContain('not the Open Montage workflow runtime')
    expect(rawSkill).toContain('skills/_shared/remotion-director-contract.md')
    expect(rawSkill).toContain('skills/_shared/visual-direction/SKILL.md')
    expect(rawSkill).toContain('skills/_shared/studio-production/taste-direction.md')
    expect(rawSkill).toContain('remotion-video-director')
    expect(rawSkill).toContain('reference only when the selected direction benefits from it')
    expect(rawSkill).toContain('creative brief')
    expect(rawSkill).toContain('layout contract')
    expect(rawSkill).toContain('Do not reduce it to a color palette or website design system')
    expect(rawSkill).toContain('Target duration: use the user')
    expect(rawSkill).toContain('If missing, make 60s')
    expect(rawSkill).toContain('The requested duration is a hard contract')
    expect(rawSkill).toContain('Start a `studio_run` before producing the creative packet')
    expect(rawSkill).toContain('put_creative_packet')
    expect(rawSkill).toContain('eight-stage CUI')
    expect(rawSkill).toContain('Do not recreate or resubmit those three JSON documents')
    expect(rawSkill).toContain('A failed Studio Run artifact write')
    expect(rawSkill).toContain('never change the video duration to match an')
    expect(rawSkill).toContain('Voiceover and an instrumental score are part of this skill by default')
    expect(rawSkill).toContain('generate narration, continuous music, ambience, and meaningful SFX')
    expect(rawSkill).toContain('Seed Audio')
    expect(rawSkill).toContain('`generate_audio({ kind: "mixed", ... })` exactly once')
    expect(rawSkill).toContain('canonical performance-score blocks')
    expect(rawSkill).toContain('`[MUSIC]`')
    expect(rawSkill).toContain('`[VOICE]`')
    expect(rawSkill).toContain('`[SFX]`')
    expect(rawSkill).toContain('`[MIX]`')
    expect(rawSkill).toContain('every spoken line')
    expect(rawSkill).toContain('co-leading layer')
    expect(rawSkill).toContain('no more than 1-2 dB of ducking')
    expect(rawSkill).toContain('Do not add a second generated audio layer after step 6')
    expect(rawSkill).toContain('Subtitles are part of this skill by default')
    expect(rawSkill).toContain('Sound design is part of the default planning pass')
    expect(rawSkill).toContain('For every narrated explainer')
    expect(rawSkill).not.toContain('When music is requested')
    expect(rawSkill).not.toContain('would make the explanation clearer or more memorable')
    expect(rawSkill).toContain('same one-pass `mixed` prompt')
    expect(rawSkill).toContain('Prompt timestamps express order and intent')
    expect(rawSkill).toContain('All new standalone audio generation uses Seed Audio')
    expect(rawSkill).not.toContain('provider: "suno"')
    expect(rawSkill).toContain('Audio Index markers such as `<<<audio_N>>>` are labels')
    expect(rawSkill).toContain('Use the returned public `audioUrl` directly in Remotion')
    expect(rawSkill).toContain('Never put `<<<audio_N>>>` inside composition props or `<Audio>`')
    expect(rawSkill).toContain('Create a compact asset-and-audio cue sheet before generating remaining')
    expect(rawSkill).toContain('Scene -> narration beat -> sound beat -> base Remotion motion')
    expect(rawSkill).toContain('Do not default to webpage structures')
    expect(rawSkill).toContain('Use time to stage, transform, and reveal the composition')
    expect(rawSkill).not.toContain('Plan 6-8 scenes')
    expect(rawSkill).not.toContain('Keep simultaneous media count low')
    expect(rawSkill).not.toContain('one main idea per scene')
    expect(rawSkill).not.toContain('one focal point per scene')
    expect(rawSkill).not.toContain('compact enough to render reliably')
    expect(rawSkill).toContain('Prefer stickers for foreground insertions')
    expect(rawSkill).toContain('Rectangular generated images are')
    expect(rawSkill).toContain('There is no')
    expect(rawSkill).toContain('fixed sticker quota')
    expect(rawSkill).toContain('use the literal 1-based')
    expect(rawSkill).toContain('never map Media Index N to the 0-based')
    expect(rawSkill).toContain('Scene Cue Sheet Pattern')
    expect(rawSkill).toContain('All Chinese,')
    expect(rawSkill).toContain('Unexpected identifier')
    expect(rawSkill).toContain('Unless the user explicitly requested no audio')
    expect(rawSkill).toContain('`transcribe_audio({ media_url: audioUrl, expected_sections:')
    expect(rawSkill).toContain('authoritative narration cue sheet')
    expect(rawSkill).toContain('planned Script')
    expect(rawSkill).toContain('ranges are not proof')
    expect(rawSkill).toContain('timing data, not a caption renderer')
    expect(rawSkill).toContain('They do not choose subtitle text styling')
    expect(rawSkill).toContain('There is no required prop name')
    expect(rawSkill).toContain('Treat subtitles as part of the visual direction')
    expect(rawSkill).toContain('default to the lower safe area, centered')
    expect(rawSkill).toContain('78-86% of the canvas')
    expect(rawSkill).toContain('semi-transparent dark background')
    expect(rawSkill).toContain('no more than 1-2 lines')
    expect(rawSkill).toContain('restrained fade, slight rise, or readable type-on')
    expect(rawSkill).toContain('scene timing plus subtitle cues must share the same')
    expect(rawSkill).toContain('Merge adjacent short cues')
    expect(rawSkill).toContain('must not cover the primary subject')
    expect(rawSkill).toContain('do not introduce a shared caption renderer')
    expect(rawSkill).toContain('Do not copy raw ASR output blindly')
    expect(rawSkill).toContain('three-way semantic match')
    expect(rawSkill).toContain('subtitleSyncEvidence')
    expect(rawSkill).toContain('before Storyboard')
    expect(rawSkill).toContain('narrationTimingEvidence')
    expect(rawSkill).toContain('actual subtitle visibility and picture alignment are')
    expect(rawSkill).toContain('verified from the representative Composition preview frames before export')
    expect(rawSkill).toContain('Do not author a separate')
    expect(rawSkill).toContain('worker projects both Review and Delivery')
    expect(rawSkill).toContain('primaryAssetId')
    expect(rawSkill).toContain('read and follow')
    expect(rawSkill).toContain('skills/sticker-maker/SKILL.md')
    expect(rawSkill).toContain('At least three `preview_frame` checks')
    expect(rawSkill).toContain('The composition is saved and published to the timeline')
    expect(rawSkill).not.toContain('awesome-design-md')
    expect(compositionPrompt).toContain('skills/_shared/speech-clock.md')
    expect(compositionPrompt.replace(/\s+/g, ' ')).toContain('authoritative Speech Clock')
    expect(compositionPrompt).toContain('Wording, grouping,')
    expect(compositionPrompt).not.toContain('props.captions` is authoritative')
    expect(rawSkill).not.toContain('generate_voiceover')
    expect(rawSkill).not.toContain('list_voiceover_voices')
    expect(rawSkill).not.toContain('generate_music')

    expect(skill?.description).toContain('explainer video')
    expect(skill?.description).toContain('longer than 15s')
    expect(rawSkill).toContain('"explainer video"')
    expect(rawSkill).toContain('"Explainer Video"')
    expect(rawSkill).toContain('"解释视频"')
    expect(rawSkill).toContain('"讲解视频"')
    expect(agent).toContain('Video duration is authoritative')
    expect(agent).toContain("For output within the selected model's single-generation limit")
    expect(agent).toContain('including explainers, product films, platform-native shorts')
    expect(agent).toContain('Beyond that limit, activate and read the matching Skill')
    expect(rawSkill).toContain('For a video up to and including 15 seconds')
    expect(rawSkill).toContain('the explainer label alone does not justify this')
  })

  it('uses the first-class Visual Asset Bridge for sticker preparation', () => {
    const sticker = read('src/skills/sticker-maker/SKILL.md')

    expect(sticker).toContain('prepare_visual_asset({')
    expect(sticker).toContain('five-background QA sheet')
    expect(sticker).toContain('enclosed high-confidence chroma pockets')
    expect(sticker).toContain('residualChromaRatio')
    expect(sticker).not.toContain('run_code({ runtime: "node" })')
    expect(sticker).not.toContain('sharp')
  })
})
