import { describe, expect, it } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';
import config from '../capacitor.config';

const root = path.resolve(__dirname, '..');

describe('iOS App Store readiness guardrails', () => {
  it('uses a bundled launch shell instead of production server.url', () => {
    expect(config.webDir).toBe('capacitor-www');
    expect(config.server?.url).toBeUndefined();
    expect(config.server?.allowNavigation).toContain('www.makaron.app');
  });

  it('keeps the native iOS webview locked to app-like viewport behavior', () => {
    expect(config.appId).toBe('app.makaron.ios');
    expect(config.zoomEnabled).toBe(false);
    expect(config.appendUserAgent).toContain('MakaronIOS');
    expect(config.plugins?.Keyboard).toMatchObject({ resize: 'none', style: 'DARK' });
  });

  it('routes Makaron iOS WebView users away from Google OAuth', () => {
    const loginPage = fs.readFileSync(path.join(root, 'src/app/login/page.tsx'), 'utf8');
    expect(loginPage).toContain('userAgentHasMakaronIOSToken');
    expect(loginPage).toContain('{!inApp &&');
  });

  it('tracks the migration acceptance criteria in docs', () => {
    const plan = fs.readFileSync(path.join(root, 'docs/ios-migration-test-plan.md'), 'utf8');
    expect(plan).toContain('Keyboard adaptation');
    expect(plan).toContain('Billing compliance');
    expect(plan).toContain('App Store Review Defaults');
    expect(plan).toContain('StoreKit');
  });

  it('bundles a local fallback shell that forwards to the production web app', () => {
    const shell = fs.readFileSync(path.join(root, 'capacitor-www/index.html'), 'utf8');
    expect(shell).toContain('viewport-fit=cover');
    expect(shell).toContain('SplashScreen');
    expect(shell).toContain('https://www.makaron.app/');
  });

  it('declares iOS permission purpose strings and portrait-only full-screen orientation', () => {
    const infoPlist = fs.readFileSync(path.join(root, 'ios/App/App/Info.plist'), 'utf8');
    expect(infoPlist).toContain('NSCameraUsageDescription');
    expect(infoPlist).toContain('NSPhotoLibraryUsageDescription');
    expect(infoPlist).toContain('NSPhotoLibraryAddUsageDescription');
    expect(infoPlist).toContain('NSMicrophoneUsageDescription');
    expect(infoPlist).toContain('NSAllowsLocalNetworking');
    expect(infoPlist).toContain('ITSAppUsesNonExemptEncryption');
    expect(infoPlist).toContain('UIRequiresFullScreen');
    expect(infoPlist).toContain('UIApplicationSceneManifest');
    expect(infoPlist).toContain('SceneDelegate');
    expect(infoPlist).not.toContain('UIInterfaceOrientationLandscapeLeft');
    expect(infoPlist).not.toContain('UIInterfaceOrientationLandscapeRight');
  });

  it('keeps local iPhone debug routing explicit and resettable', () => {
    const packageJson = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
    const helper = fs.readFileSync(path.join(root, 'tools/ios-local-config.mjs'), 'utf8');
    expect(packageJson.scripts['dev:ios']).toContain('-H 0.0.0.0');
    expect(packageJson.scripts['ios:local']).toContain('ios-local-config');
    expect(packageJson.scripts['ios:prod']).toContain('--reset');
    expect(helper).toContain('IOS_DEV_SERVER_URL');
    expect(helper).toContain('delete config.server.url');
  });

  it('keeps native safe-area padding scoped to iOS editor controls instead of the body', () => {
    const globals = fs.readFileSync(path.join(root, 'src/app/globals.css'), 'utf8');
    const editor = fs.readFileSync(path.join(root, 'src/components/Editor.tsx'), 'utf8');
    const projects = fs.readFileSync(path.join(root, 'src/app/projects/page.tsx'), 'utf8');
    const topBar = fs.readFileSync(path.join(root, 'src/components/TopBar.tsx'), 'utf8');
    const changelog = fs.readFileSync(path.join(root, 'src/components/Changelog.tsx'), 'utf8');
    expect(globals).toContain('.makaron-ios-app body');
    expect(globals).toContain('padding: 0');
    expect(globals).toContain('.makaron-ios-app .makaron-ios-page');
    expect(globals).toContain('.makaron-ios-app .makaron-editor-shell');
    expect(globals).toContain('--makaron-ios-bottom-control-inset');
    expect(globals).toContain('.makaron-ios-app .makaron-editor-bottom-bar');
    expect(globals).toContain('.makaron-ios-app .makaron-topbar');
    expect(globals).toContain('.makaron-ios-app .makaron-projects-hero');
    expect(editor).toContain('makaron-editor-shell');
    expect(editor).toContain('makaron-editor-topbar');
    expect(editor).toContain('makaron-editor-bottom-bar');
    expect(projects).toContain('makaron-projects-page');
    expect(projects).toContain('makaron-projects-hero');
    expect(projects).not.toContain('makaron-ios-projects-snapshot-html');
    expect(topBar).toContain('makaron-topbar');
    expect(changelog).toContain('makaron-ios-app');
    expect(changelog).toContain('max-h-[82dvh]');
    expect(changelog).toContain('w-full h-full sm:h-auto');
  });

  it('gives secondary iOS app pages safe top space and a normal edge-back gesture', () => {
    const bootstrap = fs.readFileSync(path.join(root, 'src/components/NativeAppBootstrap.tsx'), 'utf8');
    const dashboard = fs.readFileSync(path.join(root, 'src/app/dashboard/page.tsx'), 'utf8');
    const skills = fs.readFileSync(path.join(root, 'src/app/skills/page.tsx'), 'utf8');
    const profile = fs.readFileSync(path.join(root, 'src/app/profile/page.tsx'), 'utf8');
    const admin = fs.readFileSync(path.join(root, 'src/app/admin/page.tsx'), 'utf8');
    const adminStatus = fs.readFileSync(path.join(root, 'src/app/admin/status/page.tsx'), 'utf8');
    const agentContent = fs.readFileSync(path.join(root, 'src/components/AgentContent.tsx'), 'utf8');
    const claim = fs.readFileSync(path.join(root, 'src/app/claim/page.tsx'), 'utf8');
    const mcp = fs.readFileSync(path.join(root, 'src/app/mcp/page.tsx'), 'utf8');
    const projects = fs.readFileSync(path.join(root, 'src/app/projects/page.tsx'), 'utf8');
    const home = fs.readFileSync(path.join(root, 'src/app/home/page.tsx'), 'utf8');
    const editor = fs.readFileSync(path.join(root, 'src/components/Editor.tsx'), 'utf8');
    const topBar = fs.readFileSync(path.join(root, 'src/components/TopBar.tsx'), 'utf8');
    const creditPopup = fs.readFileSync(path.join(root, 'src/components/CreditPopup.tsx'), 'utf8');
    const nativeCache = fs.readFileSync(path.join(root, 'src/lib/native-app-cache.ts'), 'utf8');
    const projectsListWarm = fs.readFileSync(path.join(root, 'src/lib/projects-list-warm.ts'), 'utf8');
    const projectEditorCache = fs.readFileSync(path.join(root, 'src/lib/project-editor-cache.ts'), 'utf8');

    expect(bootstrap).toContain('IOS_PAGE_BACK_EDGE_PX');
    expect(bootstrap).toContain('IOS_PAGE_BACK_COMMIT_PX');
    expect(bootstrap).toContain('shouldUsePageBackGesture');
    expect(bootstrap).toContain('setPageBackOffset(dx)');
    expect(bootstrap).toContain("document.querySelector('.makaron-ios-page')");
    expect(bootstrap).toContain('translate3d(${offset}px, 0, 0)');
    expect(bootstrap).toContain("path === '/projects'");
    expect(bootstrap).toContain("path === '/home'");
    expect(bootstrap).toContain("document.querySelector('.makaron-editor-shell')");
    expect(bootstrap).toContain("document.querySelector('[data-makaron-ios-project-overlay]')");
    expect(bootstrap).toContain("document.querySelector('[data-makaron-cui-pan]')");
    expect(bootstrap).toContain('window.history.back()');
    expect(bootstrap).toContain('NATIVE_APP_PREFETCH_ROUTES');
    expect(bootstrap).toContain("'/dashboard'");
    expect(bootstrap).toContain("'/skills'");
    expect(bootstrap).toContain('router.prefetch(route)');
    expect(bootstrap).toContain('NATIVE_APP_WARM_API_PATHS');
    expect(bootstrap).toContain("'/api/billing/dashboard'");
    expect(bootstrap).toContain('warmNativeJSONCache(path)');
    expect(dashboard).toContain("readNativeJSONCache<DashboardPayload>('/api/billing/dashboard')");
    expect(dashboard).toContain("writeNativeJSONCache('/api/billing/dashboard', data)");
    expect(skills).toContain("readNativeJSONCache<SkillsPayload>('/api/skills')");
    expect(skills).toContain("writeNativeJSONCache('/api/skills', data)");
    expect(nativeCache).toContain('sessionStorage.setItem');
    expect(topBar).toContain("readNativeJSONCache<CreditsPayload>('/api/billing/credits')");
    expect(topBar).toContain("writeNativeJSONCache('/api/billing/credits', d)");
    expect(topBar).toContain('TOPBAR_ROUTE_WARM_APIS');
    expect(topBar).toContain("onPointerDown={() => warmTopBarRoute('/dashboard')}");
    expect(topBar).toContain("onPointerDown={() => warmTopBarRoute('/skills')}");
    expect(editor).toContain("readNativeJSONCache<CreditsPayload>('/api/billing/credits')");
    expect(editor).toContain("readNativeJSONCache<SkillsPayload>('/api/skills')");
    expect(editor).toContain("writeNativeJSONCache('/api/skills', d)");
    expect(home).toContain("readNativeJSONCache<HomeSkill[]>('/api/home-skills')");
    expect(home).toContain("readNativeJSONCache<SkillsPayload>('/api/skills')");
    expect(home).toContain("writeNativeJSONCache('/api/home-skills', data)");
    expect(projects).toContain("readNativeJSONCache<CreditsPayload>('/api/billing/credits')");
    expect(projects).toContain("readNativeJSONCache<SkillsPayload>('/api/skills')");
    expect(projectsListWarm).toContain('warmProjectsListCache');
    expect(projectsListWarm).toContain('cacheProjectsList(userId, projects)');
    expect(topBar).toContain('warmProjectsListCache(user.id)');
    expect(creditPopup).toContain("writeNativeJSONCache('/api/billing/credits', data)");
    expect(projectEditorCache).toContain('warmProjectEditorCache');
    expect(projectEditorCache).toContain('cacheProjectData');
    expect(projects).toContain('warmProjectEditorCaches(projects.map((project) => project.id), userId, 6)');
    expect(projects).toContain('onTouchStart={onWarm}');
    expect(projects).toContain('onPointerEnter={onWarm}');
    expect(bootstrap).toContain('pickMediaFromNativePhotoLibrary');
    expect(bootstrap).toContain('acceptsNativePhotoPicker');
    expect(bootstrap).toContain("input.dispatchEvent(new Event('change'");
    expect(bootstrap).not.toContain('document.body.style.transform');
    expect(bootstrap).not.toContain('cloneNode');
    expect(dashboard).toContain('makaron-ios-page');
    expect(skills).toContain('makaron-ios-page');
    expect(profile).toContain('makaron-ios-page');
    expect(admin).toContain('makaron-ios-page');
    expect(adminStatus).toContain('makaron-ios-page');
    expect(agentContent).toContain('makaron-ios-page');
    expect(claim).toContain('makaron-ios-page');
    expect(mcp).toContain('makaron-ios-page');
  });

  it('saves editor images and videos through native Photos on iOS before web fallbacks', () => {
    const bridge = fs.readFileSync(path.join(root, 'ios/App/App/MakaronBridgeViewController.swift'), 'utf8');
    const nativeMedia = fs.readFileSync(path.join(root, 'src/lib/native-media.ts'), 'utf8');
    const download = fs.readFileSync(path.join(root, 'src/lib/editor/download.ts'), 'utf8');

    expect(bridge).toContain('WKScriptMessageHandler');
    expect(bridge).toContain('PHPickerViewControllerDelegate');
    expect(bridge).toContain('PHPhotoLibrary');
    expect(bridge).toContain('PHPickerViewController');
    expect(bridge).toContain('makaronNative');
    expect(bridge).toContain('saveToPhotos');
    expect(bridge).toContain('pickMedia');
    expect(bridge).toContain('PHAssetCreationRequest.forAsset()');
    expect(bridge).toContain('UIImage(data: data)');
    expect(bridge).toContain('jpegData(compressionQuality: 0.95)');
    expect(bridge).toContain('jpegFilename(for: filename)');
    expect(bridge).toContain('placeholderForCreatedAsset?.localIdentifier');
    expect(bridge).toContain('[Makaron] native save request');
    expect(bridge).toContain('[Makaron] native save image result');
    expect(bridge).toContain('[Makaron] native response');
    expect(bridge).toContain("window.dispatchEvent(new CustomEvent('makaron-native-response'");
    expect(nativeMedia).toContain('isNativePhotoLibrarySaveAvailable');
    expect(nativeMedia).toContain('isNativePhotoLibraryPickerAvailable');
    expect(nativeMedia).toContain('saveBlobToNativePhotoLibrary');
    expect(nativeMedia).toContain('saveUrlToNativePhotoLibrary');
    expect(nativeMedia).toContain('pickMediaFromNativePhotoLibrary');
    expect(nativeMedia).toContain('makaron:native-media:last-result');
    expect(nativeMedia).toContain("phase: 'sent'");
    expect(nativeMedia).toContain("phase: 'timeout'");
    expect(nativeMedia).toContain('IMAGE_SAVE_TIMEOUT_MS');
    expect(nativeMedia).toContain('webkit?.messageHandlers?.makaronNative');
    expect(download).toContain('isNativePhotoLibrarySaveAvailable');
    expect(download).toContain('normalizeImageBlobForNativeSave');
    expect(download).toContain('isRemoteHttpUrl(img)');
    expect(download).toContain('saveUrlToNativePhotoLibrary(img');
    expect(download).toContain("canvas.toBlob((result) =>");
    expect(download).toContain("'image/jpeg', 0.95");
    expect(download).toContain('saveBlobToNativePhotoLibrary');
    expect(download).toContain('saveUrlToNativePhotoLibrary');
  });

  it('routes native keyboard height into the CUI input bar', () => {
    const bootstrap = fs.readFileSync(path.join(root, 'src/components/NativeAppBootstrap.tsx'), 'utf8');
    const chat = fs.readFileSync(path.join(root, 'src/components/AgentChatView.tsx'), 'utf8');
    expect(bootstrap).toContain('makaron-keyboard-inset-change');
    expect(bootstrap).toContain('nativeKeyboardInset');
    expect(bootstrap).toContain('viewportKeyboardInset');
    expect(bootstrap).toContain('Math.max(nativeKeyboardInset, viewportKeyboardInset)');
    expect(chat).toContain('nativeKbInset');
    expect(chat).toContain('effectiveKbInset');
    expect(chat).toContain('keyboardInsetCss');
    expect(chat).toContain('var(--makaron-native-keyboard-inset');
    expect(chat).toContain('calc(${inputBarH}px + ${keyboardInsetCss})');
  });

  it('keeps iOS home skill detail back swipe scoped to the skill overlay', () => {
    const homePage = fs.readFileSync(path.join(root, 'src/app/home/page.tsx'), 'utf8');
    expect(homePage).toContain('isMakaronIOSApp');
    expect(homePage).toContain('usePathname');
    expect(homePage).toContain('const [isIOSAppShell] = useState(() => isMakaronIOSApp())');
    expect(homePage).toContain('detailPathActiveRef');
    expect(homePage).toContain('IOS_SKILL_BACK_EDGE_PX');
    expect(homePage).toContain('IOS_SKILL_BACK_COMMIT_PX');
    expect(homePage).toContain('closeSkillDetail');
    expect(homePage).toContain('handleSkillBackPanStart');
    expect(homePage).toContain('handleSkillBackPanMove');
    expect(homePage).toContain('handleSkillBackPanEnd');
    expect(homePage).toContain('onTouchStartCapture={handleSkillBackPanStart}');
    expect(homePage).toContain('onTouchMoveCapture={handleSkillBackPanMove}');
    expect(homePage).toContain('onTouchEndCapture={handleSkillBackPanEnd}');
    expect(homePage).toContain("window.addEventListener('popstate', onPop)");
    expect(homePage).toContain("window.history.pushState(null, '', `/home/${template.id}`)");
    expect(homePage).toContain("window.history.replaceState(null, '', `/home/${t.id}`)");
    expect(homePage).not.toContain('document.body.style.transform');
    expect(homePage).not.toContain('cloneNode');
    expect(homePage).not.toContain('makaron-ios-project');
  });

  it('keeps iOS project navigation inside a live projects-page overlay while preserving CUI pan close', () => {
    const editor = fs.readFileSync(path.join(root, 'src/components/Editor.tsx'), 'utf8');
    const bootstrap = fs.readFileSync(path.join(root, 'src/components/NativeAppBootstrap.tsx'), 'utf8');
    const projectsPage = fs.readFileSync(path.join(root, 'src/app/projects/page.tsx'), 'utf8');
    const projectPage = fs.readFileSync(path.join(root, 'src/app/projects/[id]/page.tsx'), 'utf8');
    const projectContainer = fs.readFileSync(path.join(root, 'src/components/ProjectEditorContainer.tsx'), 'utf8');
    const imageCache = fs.readFileSync(path.join(root, 'src/lib/imageCache.ts'), 'utf8');
    const storage = fs.readFileSync(path.join(root, 'src/lib/supabase/storage.ts'), 'utf8');
    const bridge = fs.readFileSync(path.join(root, 'ios/App/App/MakaronBridgeViewController.swift'), 'utf8');
    const storyboard = fs.readFileSync(path.join(root, 'ios/App/App/Base.lproj/Main.storyboard'), 'utf8');
    const project = fs.readFileSync(path.join(root, 'ios/App/App.xcodeproj/project.pbxproj'), 'utf8');
    const projectLoading = path.join(root, 'src/app/projects/[id]/loading.tsx');
    expect(editor).toContain('hasCuiHistoryState');
    expect(editor).toContain("window.addEventListener('popstate', handlePop)");
    expect(editor).toContain("viewMode === 'cui'");
    expect(editor).toContain('disableAgentLiveReload');
    expect(editor).toContain('window.clearTimeout(reloadTimer)');
    expect(editor).toContain('disableBodyScrollLock');
    expect(editor).toContain('inactive?: boolean');
    expect(editor).toContain('inactive = false');
    expect(editor).toContain('if (inactive) return');
    expect(editor).not.toContain('edgeSwipeBackRef');
    expect(editor).not.toContain('makaron-native-back');
    expect(bootstrap).not.toContain('installIOSBackSwipe');
    expect(bootstrap).not.toContain('IOS_BACK_SWIPE_EDGE_PX');
    expect(bootstrap).not.toContain('document.body.style.transform');
    expect(bootstrap).toContain('__makaronNativeBootId');
    expect(bootstrap).toContain('NATIVE_BOOT_LOG_SESSION_KEY');
    expect(bootstrap).toContain('[makaron-ios-native] boot');
    expect(projectsPage).toContain('data-makaron-ios-project-overlay');
    expect(projectsPage).toContain('activeIOSProjectId');
    expect(projectsPage).toContain('renderedIOSProjectId');
    expect(projectsPage).toContain('renderedIOSProjectIdRef');
    expect(projectsPage).toContain('projectsRef');
    expect(projectsPage).toContain('const currentProjects = projectsRef.current');
    expect(projectsPage).toContain('loadingProjectsRef');
    expect(projectsPage).toContain('needsInitialProjects');
    expect(projectsPage).toContain('duringFrozenReturn');
    expect(projectsPage).toContain('docHeight');
    expect(projectsPage).toContain('hasHiddenEditor');
    expect(projectsPage).toContain('editor-retained-hidden-after-return');
    expect(projectsPage).not.toContain('IOS_PROJECT_EDITOR_UNMOUNT_DELAY_MS');
    expect(projectsPage).not.toContain('iosProjectUnmountTimerRef');
    expect(projectsPage).not.toContain('clearIOSProjectUnmountTimer');
    expect(projectsPage).not.toContain('editor-hidden-after-return');
    expect(projectsPage).not.toContain('editor-unmounted-after-return');
    expect(projectsPage).not.toContain('setRenderedIOSProjectId(null)');
    expect(projectsPage).toContain('iosProjectScrollYRef');
    expect(projectsPage).toContain('pendingIOSProjectsRefreshRef');
    expect(projectsPage).toContain('iosProjectNavGenerationRef');
    expect(projectsPage).toContain('projects-fetch-discarded-nav-generation-changed');
    expect(projectsPage).toContain('refreshIOSProjectCard');
    expect(projectsPage).toContain('project-card-refreshed-after-return');
    expect(projectsPage).toContain('projects-background-refresh-requested');
    expect(projectsPage).toContain('projects-stashed-refresh-applied');
    expect(projectsPage).toContain('projectsRefreshNonce');
    expect(projectsPage).toContain('iosProjectRefreshSelfTest');
    expect(projectsPage).toContain('refresh-self-test-pass');
    expect(projectsPage).toContain('data-snapshot-count');
    expect(projectsPage).toContain('iosReturnSelfTest');
    expect(projectsPage).toContain('return-self-test-pass');
    expect(projectsPage).toContain('iosProjectClosingRef');
    expect(projectsPage).toContain('close-project-ignored-already-closing');
    expect(projectsPage).toContain('IOS_PROJECT_RETURN_REFRESH_GUARD_MS');
    expect(projectsPage).toContain('IOS_PROJECT_AUTH_GRACE_MS');
    expect(projectsPage).toContain('iosProjectReturnFreezeUntilRef');
    expect(projectsPage).toContain('iosProjectAuthGraceUntilRef');
    expect(projectsPage).toContain('canHoldIOSProjectsDuringAuthGap');
    expect(projectsPage).toContain('canHoldCachedIOSProjectsWithoutUser');
    expect(projectsPage).toContain('auth-gap-held-after-return');
    expect(projectsPage).toContain('auth-empty-held-with-cached-projects');
    expect(projectsPage).toContain('applyProjectsRefresh');
    expect(projectsPage).not.toContain('retainedProjectId: renderedIOSProjectIdRef.current');
    expect(projectsPage).not.toContain('|| renderedIOSProjectIdRef.current');
    expect(projectsPage).not.toContain('iosProjectsPageFrozen');
    expect(projectsPage).not.toContain('iosProjectReturnFrozen');
    expect(projectsPage).not.toContain('data-makaron-ios-project-freeze-spacer');
    expect(projectsPage).not.toContain("top: `-${iosProjectScrollYRef.current}px`");
    expect(projectsPage).not.toContain("position: 'fixed' as const");
    expect(projectsPage).toContain("visibility: activeIOSProjectId ? 'visible' : 'hidden'");
    expect(projectsPage).toContain("contentVisibility: activeIOSProjectId ? 'visible' : 'hidden'");
    expect(projectsPage).toContain("pointerEvents: activeIOSProjectId ? 'auto' : 'none'");
    expect(projectsPage).toContain("contain: 'layout paint'");
    expect(projectsPage).not.toContain("contain: 'layout paint style'");
    expect(projectsPage).toContain("isolation: 'isolate'");
    expect(projectsPage).toContain('blockNativeBackSwipe');
    expect(projectsPage).toContain('passive: false');
    expect(projectsPage).toContain("overscrollBehaviorX: 'contain'");
    expect(projectsPage).toContain('isMakaronIOSAppShell');
    expect(projectsPage).toContain('.Capacitor');
    expect(projectsPage).toContain('getLastProjectsListSync');
    expect(projectsPage).toContain('canRenderCachedIOSProjectsWhileAuthPending');
    expect(projectsPage).toContain('(authLoading || canHoldIOSProjectsDuringAuthGap || canHoldCachedIOSProjectsWithoutUser)');
    expect(projectsPage).toContain('__makaronIOSProjectNavLog');
    expect(projectsPage).toContain('IOS_PROJECT_NAV_LOG_SESSION_KEY');
    expect(projectsPage).toContain('[ios-project-nav]');
    expect(projectsPage).toContain('useState(() => isMakaronIOSAppShell())');
    expect(projectsPage).toContain('useIOSInlineProjectNavigation');
    expect(projectsPage).not.toContain('useSearchParams');
    expect(projectsPage).not.toContain("searchParams.get('iosProject')");
    expect(projectsPage).not.toContain('open-project-from-route-handoff');
    expect(projectsPage).not.toContain('iosProjectParam');
    expect(projectsPage).not.toContain('?iosProject=');
    expect(projectsPage).toContain('useInlineNavigation');
    expect(projectsPage).toContain('role="link"');
    expect(projectsPage).toContain('isCuiOpen');
    expect(projectsPage).not.toContain('makaronProjectOverlay');
    expect(projectsPage).not.toContain("window.addEventListener('popstate'");
    expect(projectsPage).not.toContain('window.history.back()');
    expect(projectsPage).not.toContain('document.body.style.overflow');
    expect(projectsPage).not.toContain('document.body.style.position');
    expect(projectsPage).not.toContain('window.location.reload');
    expect(projectsPage).not.toContain('`/projects/${projectId}`');
    expect(projectsPage).not.toContain("router.push('/projects')");
    expect(projectsPage).not.toContain("router.replace('/projects')");
    expect(projectsPage).toContain('ProjectEditorContainer');
    expect(projectsPage).toContain('disableAgentLiveReload');
    expect(projectsPage).toContain('disableBodyScrollLock');
    expect(projectsPage).toContain('isInlineActive={activeIOSProjectId === renderedIOSProjectId}');
    expect(projectsPage).toContain('if (useIOSInlineProjectNavigation)');
    expect(projectsPage).toContain('openIOSProject(result.projectId)');
    expect(projectsPage).toContain('useIOSSafeImageUrls={useIOSInlineProjectNavigation}');
    expect(projectsPage).toContain('getOriginFormatThumbnailUrl(lastSnap.image_url, 400, 50, 400)');
    expect(storage).toContain("'format=origin'");
    expect(projectsPage).toContain('useState(useIOSSafeImageUrls)');
    expect(projectsPage).toContain("animationDelay: useIOSSafeImageUrls ? undefined");
    expect(projectsPage).toContain("transition: useIOSSafeImageUrls ? 'none'");
    expect(projectsPage).toContain('loading={index < 4 ?');
    expect(projectsPage).toContain('decoding="async"');
    expect(bootstrap).not.toContain('makaron-ios-projects-snapshot-html');
    expect(projectsPage).not.toContain('makaron-ios-projects-snapshot-html');
    expect(bootstrap).not.toContain('data-makaron-ios-back-overlay');
    expect(projectsPage).not.toContain('data-makaron-ios-back-overlay');
    expect(bootstrap).not.toContain('cloneNode');
    expect(projectsPage).not.toContain('cloneNode');
    expect(bootstrap).not.toContain('makaron-ios-project-back');
    expect(editor).toContain('data-makaron-cui-pan');
    expect(editor).toContain('IOS_CUI_PAN_COMMIT_PX');
    expect(editor).not.toContain('shouldPlayIOSProjectPush');
    expect(editor).not.toContain('data-makaron-ios-projects-backdrop');
    expect(projectPage).toContain('ProjectEditorContainer');
    expect(projectPage).not.toContain('isMakaronIOSApp');
    expect(projectPage).not.toContain('shouldHandoffIOSProjectRouteToOverlay');
    expect(projectPage).not.toContain('handoff-route-to-overlay');
    expect(projectPage).not.toContain('router.replace(`/projects?iosProject=');
    expect(projectPage).not.toContain('?iosProject=');
    expect(projectPage).not.toContain('IOS_PROJECT_BACK_EVENT');
    expect(projectContainer).toContain('getCachedProjectDataSync');
    expect(projectContainer).toContain('onProjectCreated');
    expect(projectContainer).toContain('disableAgentLiveReload');
    expect(projectContainer).toContain('disableBodyScrollLock');
    expect(projectContainer).toContain('isInlineActive?: boolean');
    expect(projectContainer).toContain('if (!isInlineActive) return');
    expect(projectContainer).toContain('inactive={!isInlineActive}');
    expect(projectContainer).toContain('const leaveEditor = useCallback');
    expect(projectContainer).toContain('if (onBack)');
    expect(projectContainer).toContain('onBack()');
    expect(projectContainer).toContain('if (navigatingRef.current) return');
    expect(projectContainer).not.toContain('updateCover');
    expect(imageCache).toContain('PROJECTS_LIST_SESSION_KEY');
    expect(imageCache).toContain('getLastProjectsListSync');
    expect(imageCache).toContain('sessionStorage.setItem(PROJECTS_LIST_SESSION_KEY');
    expect(imageCache).toContain('sessionStorage.removeItem(PROJECTS_LIST_SESSION_KEY');
    expect(fs.existsSync(projectLoading)).toBe(false);
    expect(bridge).not.toContain('interactiveBackEdgeView');
    expect(bridge).not.toContain('UIPanGestureRecognizer');
    expect(bridge).toContain('allowsBackForwardNavigationGestures = false');
    expect(bridge).toContain('contentInsetAdjustmentBehavior = .never');
    expect(bridge).not.toContain('dispatchNativeBackEvent');
    expect(storyboard).toContain('MakaronBridgeViewController');
    expect(project).toContain('MakaronBridgeViewController.swift in Sources');
    expect(project).toContain('SceneDelegate.swift in Sources');
  });

  it('bundles a privacy manifest with required UserDefaults reason', () => {
    const privacy = fs.readFileSync(path.join(root, 'ios/App/App/PrivacyInfo.xcprivacy'), 'utf8');
    const project = fs.readFileSync(path.join(root, 'ios/App/App.xcodeproj/project.pbxproj'), 'utf8');
    expect(privacy).toContain('NSPrivacyAccessedAPICategoryUserDefaults');
    expect(privacy).toContain('CA92.1');
    expect(privacy).toContain('NSPrivacyTracking');
    expect(project).toContain('PrivacyInfo.xcprivacy in Resources');
  });
});
